// Code generated by qtc from "mapping.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/golang/mapping.qtpl:1
package golang

//line templates/golang/mapping.qtpl:1
import "github.com/apibrew/apibrew/pkg/model"

//line templates/golang/mapping.qtpl:2
import "strings"

//line templates/golang/mapping.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/golang/mapping.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/golang/mapping.qtpl:4
func StreamPropertyTo(qw422016 *qt422016.Writer, resource *model.Resource, property *model.ResourceProperty, isCollectionItem bool, varName string) {
//line templates/golang/mapping.qtpl:4
	qw422016.N().S(`    var `)
//line templates/golang/mapping.qtpl:5
	qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:5
	qw422016.N().S(`_mapped interface{}

`)
//line templates/golang/mapping.qtpl:7
	if property.Type == model.ResourceProperty_ENUM {
//line templates/golang/mapping.qtpl:7
		qw422016.N().S(`         `)
//line templates/golang/mapping.qtpl:8
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:8
		qw422016.N().S(`_mapped = string(`)
//line templates/golang/mapping.qtpl:8
		StreamNormalizePointer(qw422016, property, varName, isCollectionItem, false)
//line templates/golang/mapping.qtpl:8
		qw422016.N().S(`)
`)
//line templates/golang/mapping.qtpl:9
	} else if property.Type == model.ResourceProperty_STRUCT {
//line templates/golang/mapping.qtpl:9
		qw422016.N().S(`            `)
//line templates/golang/mapping.qtpl:10
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:10
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping.qtpl:10
		StreamGoName(qw422016, getSubTypeNameByProperty(resource, property))
//line templates/golang/mapping.qtpl:10
		qw422016.N().S(`MapperInstance.ToProperties(`)
//line templates/golang/mapping.qtpl:10
		StreamNormalizePointer(qw422016, property, varName, isCollectionItem, true)
//line templates/golang/mapping.qtpl:10
		qw422016.N().S(`)
`)
//line templates/golang/mapping.qtpl:11
	} else if property.Type == model.ResourceProperty_MAP {
//line templates/golang/mapping.qtpl:11
		qw422016.N().S(`        var `)
//line templates/golang/mapping.qtpl:12
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:12
		qw422016.N().S(`_st = make(map[string]interface{})
        for key, value := range `)
//line templates/golang/mapping.qtpl:13
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:13
		qw422016.N().S(` {
            `)
//line templates/golang/mapping.qtpl:14
		subVarName := "var_1x"

//line templates/golang/mapping.qtpl:14
		qw422016.N().S(`
            `)
//line templates/golang/mapping.qtpl:15
		qw422016.E().S(subVarName)
//line templates/golang/mapping.qtpl:15
		qw422016.N().S(` := value
            `)
//line templates/golang/mapping.qtpl:16
		StreamPropertyTo(qw422016, resource, property.Item, true, subVarName)
//line templates/golang/mapping.qtpl:16
		qw422016.N().S(`
            `)
//line templates/golang/mapping.qtpl:17
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:17
		qw422016.N().S(`_st[key] = `)
//line templates/golang/mapping.qtpl:17
		qw422016.E().S(subVarName)
//line templates/golang/mapping.qtpl:17
		qw422016.N().S(`_mapped
        }
        `)
//line templates/golang/mapping.qtpl:19
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:19
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping.qtpl:19
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:19
		qw422016.N().S(`_st
`)
//line templates/golang/mapping.qtpl:20
	} else if property.Type == model.ResourceProperty_LIST {
//line templates/golang/mapping.qtpl:20
		qw422016.N().S(`        var `)
//line templates/golang/mapping.qtpl:21
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:21
		qw422016.N().S(`_l []interface{}
        for _, value := range `)
//line templates/golang/mapping.qtpl:22
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:22
		qw422016.N().S(` {
            `)
//line templates/golang/mapping.qtpl:23
		subVarName := "var_5x"

//line templates/golang/mapping.qtpl:23
		qw422016.N().S(`
            `)
//line templates/golang/mapping.qtpl:24
		qw422016.E().S(subVarName)
//line templates/golang/mapping.qtpl:24
		qw422016.N().S(` := value
            `)
//line templates/golang/mapping.qtpl:25
		StreamPropertyTo(qw422016, resource, property.Item, true, subVarName)
//line templates/golang/mapping.qtpl:25
		qw422016.N().S(`
            `)
//line templates/golang/mapping.qtpl:26
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:26
		qw422016.N().S(`_l = append(`)
//line templates/golang/mapping.qtpl:26
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:26
		qw422016.N().S(`_l, `)
//line templates/golang/mapping.qtpl:26
		qw422016.E().S(subVarName)
//line templates/golang/mapping.qtpl:26
		qw422016.N().S(`_mapped)
        }
        `)
//line templates/golang/mapping.qtpl:28
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:28
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping.qtpl:28
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:28
		qw422016.N().S(`_l
`)
//line templates/golang/mapping.qtpl:29
	} else if property.Type == model.ResourceProperty_REFERENCE {
//line templates/golang/mapping.qtpl:29
		qw422016.N().S(`        `)
//line templates/golang/mapping.qtpl:30
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:30
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping.qtpl:30
		StreamGoName(qw422016, property.Reference.Resource)
//line templates/golang/mapping.qtpl:30
		qw422016.N().S(`MapperInstance.ToProperties(`)
//line templates/golang/mapping.qtpl:30
		StreamNormalizePointer(qw422016, property, varName, isCollectionItem, true)
//line templates/golang/mapping.qtpl:30
		qw422016.N().S(`)
`)
//line templates/golang/mapping.qtpl:31
	} else {
//line templates/golang/mapping.qtpl:31
		qw422016.N().S(`        `)
//line templates/golang/mapping.qtpl:32
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:32
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping.qtpl:32
		StreamNormalizePointer(qw422016, property, varName, isCollectionItem, false)
//line templates/golang/mapping.qtpl:32
		qw422016.N().S(`
`)
//line templates/golang/mapping.qtpl:33
	}
//line templates/golang/mapping.qtpl:34
}

//line templates/golang/mapping.qtpl:34
func WritePropertyTo(qq422016 qtio422016.Writer, resource *model.Resource, property *model.ResourceProperty, isCollectionItem bool, varName string) {
//line templates/golang/mapping.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/golang/mapping.qtpl:34
	StreamPropertyTo(qw422016, resource, property, isCollectionItem, varName)
//line templates/golang/mapping.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line templates/golang/mapping.qtpl:34
}

//line templates/golang/mapping.qtpl:34
func PropertyTo(resource *model.Resource, property *model.ResourceProperty, isCollectionItem bool, varName string) string {
//line templates/golang/mapping.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/golang/mapping.qtpl:34
	WritePropertyTo(qb422016, resource, property, isCollectionItem, varName)
//line templates/golang/mapping.qtpl:34
	qs422016 := string(qb422016.B)
//line templates/golang/mapping.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/golang/mapping.qtpl:34
	return qs422016
//line templates/golang/mapping.qtpl:34
}

//line templates/golang/mapping.qtpl:39
func StreamGenerateResourceMappingCode(qw422016 *qt422016.Writer, pkg string, resource *model.Resource, resources []*model.Resource) {
//line templates/golang/mapping.qtpl:39
	qw422016.N().S(`
`)
//line templates/golang/mapping.qtpl:41
	StreamGenerateResourceMappingHeaderCode(qw422016, pkg, resource, resources)
//line templates/golang/mapping.qtpl:41
	qw422016.N().S(`
`)
//line templates/golang/mapping.qtpl:42
	StreamGenerateResourceMappingBodyCode(qw422016, pkg, resource, GoName(resource.Name), resource.Properties, resources)
//line templates/golang/mapping.qtpl:42
	qw422016.N().S(`

`)
//line templates/golang/mapping.qtpl:44
	for _, subType := range getAllSubTypes(resource) {
//line templates/golang/mapping.qtpl:45
		typeName := GoName(getSubTypeName(resource, subType))

//line templates/golang/mapping.qtpl:46
		StreamGenerateResourceMappingBodyCode(qw422016, pkg, resource, typeName, subType.Properties, resources)
//line templates/golang/mapping.qtpl:46
		qw422016.N().S(`
`)
//line templates/golang/mapping.qtpl:47
	}
//line templates/golang/mapping.qtpl:47
	qw422016.N().S(`
`)
//line templates/golang/mapping.qtpl:49
}

//line templates/golang/mapping.qtpl:49
func WriteGenerateResourceMappingCode(qq422016 qtio422016.Writer, pkg string, resource *model.Resource, resources []*model.Resource) {
//line templates/golang/mapping.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/golang/mapping.qtpl:49
	StreamGenerateResourceMappingCode(qw422016, pkg, resource, resources)
//line templates/golang/mapping.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line templates/golang/mapping.qtpl:49
}

//line templates/golang/mapping.qtpl:49
func GenerateResourceMappingCode(pkg string, resource *model.Resource, resources []*model.Resource) string {
//line templates/golang/mapping.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/golang/mapping.qtpl:49
	WriteGenerateResourceMappingCode(qb422016, pkg, resource, resources)
//line templates/golang/mapping.qtpl:49
	qs422016 := string(qb422016.B)
//line templates/golang/mapping.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/golang/mapping.qtpl:49
	return qs422016
//line templates/golang/mapping.qtpl:49
}

//line templates/golang/mapping.qtpl:52
func StreamGenerateResourceMappingHeaderCode(qw422016 *qt422016.Writer, pkg string, resource *model.Resource, resources []*model.Resource) {
//line templates/golang/mapping.qtpl:53
	pkgParts := strings.Split(pkg, "/")

//line templates/golang/mapping.qtpl:54
	pkgName := pkgParts[len(pkgParts)-1]

//line templates/golang/mapping.qtpl:54
	qw422016.N().S(`// Code generated by apbr generate. DO NOT EDIT.
// versions:
// 	apbr generate v1.2

//go:build !codeanalysis
package `)
//line templates/golang/mapping.qtpl:60
	qw422016.E().S(pkgName)
//line templates/golang/mapping.qtpl:60
	qw422016.N().S(`

import (
    "github.com/apibrew/apibrew/pkg/model"
    "github.com/apibrew/apibrew/pkg/types"
    "github.com/apibrew/apibrew/pkg/abs"
)

`)
//line templates/golang/mapping.qtpl:68
	for _, importLine := range getImportsForMapping(resource) {
//line templates/golang/mapping.qtpl:68
		qw422016.N().S(`import "`)
//line templates/golang/mapping.qtpl:69
		qw422016.E().S(importLine)
//line templates/golang/mapping.qtpl:69
		qw422016.N().S(`"
`)
//line templates/golang/mapping.qtpl:70
	}
//line templates/golang/mapping.qtpl:71
}

//line templates/golang/mapping.qtpl:71
func WriteGenerateResourceMappingHeaderCode(qq422016 qtio422016.Writer, pkg string, resource *model.Resource, resources []*model.Resource) {
//line templates/golang/mapping.qtpl:71
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/golang/mapping.qtpl:71
	StreamGenerateResourceMappingHeaderCode(qw422016, pkg, resource, resources)
//line templates/golang/mapping.qtpl:71
	qt422016.ReleaseWriter(qw422016)
//line templates/golang/mapping.qtpl:71
}

//line templates/golang/mapping.qtpl:71
func GenerateResourceMappingHeaderCode(pkg string, resource *model.Resource, resources []*model.Resource) string {
//line templates/golang/mapping.qtpl:71
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/golang/mapping.qtpl:71
	WriteGenerateResourceMappingHeaderCode(qb422016, pkg, resource, resources)
//line templates/golang/mapping.qtpl:71
	qs422016 := string(qb422016.B)
//line templates/golang/mapping.qtpl:71
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/golang/mapping.qtpl:71
	return qs422016
//line templates/golang/mapping.qtpl:71
}

//line templates/golang/mapping.qtpl:73
func StreamGenerateResourceMappingBodyCode(qw422016 *qt422016.Writer, pkg string, resource *model.Resource, typeName string, properties []*model.ResourceProperty, resources []*model.Resource) {
//line templates/golang/mapping.qtpl:73
	qw422016.N().S(`type `)
//line templates/golang/mapping.qtpl:74
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:74
	qw422016.N().S(`Mapper struct {
}

func New`)
//line templates/golang/mapping.qtpl:77
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:77
	qw422016.N().S(`Mapper() *`)
//line templates/golang/mapping.qtpl:77
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:77
	qw422016.N().S(`Mapper {
    return &`)
//line templates/golang/mapping.qtpl:78
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:78
	qw422016.N().S(`Mapper{}
}

var `)
//line templates/golang/mapping.qtpl:81
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:81
	qw422016.N().S(`MapperInstance = New`)
//line templates/golang/mapping.qtpl:81
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:81
	qw422016.N().S(`Mapper()

func (m *`)
//line templates/golang/mapping.qtpl:83
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:83
	qw422016.N().S(`Mapper) New() *`)
//line templates/golang/mapping.qtpl:83
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:83
	qw422016.N().S(` {
    return &`)
//line templates/golang/mapping.qtpl:84
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:84
	qw422016.N().S(`{}
}

func (m *`)
//line templates/golang/mapping.qtpl:87
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:87
	qw422016.N().S(`Mapper) ResourceIdentity() abs.ResourceIdentity {
    return abs.ResourceIdentity{
       Namespace: "`)
//line templates/golang/mapping.qtpl:89
	qw422016.E().S(resource.Namespace)
//line templates/golang/mapping.qtpl:89
	qw422016.N().S(`",
       Name: "`)
//line templates/golang/mapping.qtpl:90
	qw422016.E().S(resource.Name)
//line templates/golang/mapping.qtpl:90
	qw422016.N().S(`",
    }
}

`)
//line templates/golang/mapping.qtpl:94
	if typeName == resource.Name {
//line templates/golang/mapping.qtpl:94
		qw422016.N().S(`
func (m *`)
//line templates/golang/mapping.qtpl:95
		qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:95
		qw422016.N().S(`Mapper) ToRecord(`)
//line templates/golang/mapping.qtpl:95
		StreamGoVarName(qw422016, typeName)
//line templates/golang/mapping.qtpl:95
		qw422016.N().S(` *`)
//line templates/golang/mapping.qtpl:95
		qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:95
		qw422016.N().S(`) abs.RecordLike {
    return abs.NewRecordLikeWithProperties(m.ToProperties(`)
//line templates/golang/mapping.qtpl:96
		StreamGoVarName(qw422016, typeName)
//line templates/golang/mapping.qtpl:96
		qw422016.N().S(`))
}

func (m *`)
//line templates/golang/mapping.qtpl:99
		qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:99
		qw422016.N().S(`Mapper) FromRecord(record abs.RecordLike) *`)
//line templates/golang/mapping.qtpl:99
		qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:99
		qw422016.N().S(`  {
    return m.FromProperties(record.MapCopy())
}
`)
//line templates/golang/mapping.qtpl:102
	}
//line templates/golang/mapping.qtpl:102
	qw422016.N().S(`

func (m *`)
//line templates/golang/mapping.qtpl:104
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:104
	qw422016.N().S(`Mapper) ToProperties(`)
//line templates/golang/mapping.qtpl:104
	StreamGoVarName(qw422016, typeName)
//line templates/golang/mapping.qtpl:104
	qw422016.N().S(` *`)
//line templates/golang/mapping.qtpl:104
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:104
	qw422016.N().S(`) map[string]interface{} {
    var properties = make(map[string]interface{})

`)
//line templates/golang/mapping.qtpl:107
	for _, property := range properties {
//line templates/golang/mapping.qtpl:107
		qw422016.N().S(`    `)
//line templates/golang/mapping.qtpl:108
		varName := "var_" + GoName(property.Name)

//line templates/golang/mapping.qtpl:108
		qw422016.N().S(`
    `)
//line templates/golang/mapping.qtpl:109
		qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:109
		qw422016.N().S(` := `)
//line templates/golang/mapping.qtpl:109
		StreamGoVarName(qw422016, typeName)
//line templates/golang/mapping.qtpl:109
		qw422016.N().S(`.`)
//line templates/golang/mapping.qtpl:109
		StreamGoName(qw422016, property.Name)
//line templates/golang/mapping.qtpl:109
		qw422016.N().S(`

`)
//line templates/golang/mapping.qtpl:111
		if isNullable(property) {
//line templates/golang/mapping.qtpl:111
			qw422016.N().S(`    if `)
//line templates/golang/mapping.qtpl:112
			qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:112
			qw422016.N().S(` != nil {
`)
//line templates/golang/mapping.qtpl:113
			StreamPropertyTo(qw422016, resource, property, false, varName)
//line templates/golang/mapping.qtpl:113
			qw422016.N().S(`
        `)
//line templates/golang/mapping.qtpl:115
			qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:115
			qw422016.N().S(`_packed, err := types.ByResourcePropertyType(model.ResourceProperty_`)
//line templates/golang/mapping.qtpl:115
			qw422016.E().S(property.Type.String())
//line templates/golang/mapping.qtpl:115
			qw422016.N().S(`).Pack(`)
//line templates/golang/mapping.qtpl:115
			qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:115
			qw422016.N().S(`_mapped)

        if err != nil {
            panic(err)
        }

        properties["`)
//line templates/golang/mapping.qtpl:121
			qw422016.E().S(property.Name)
//line templates/golang/mapping.qtpl:121
			qw422016.N().S(`"] = `)
//line templates/golang/mapping.qtpl:121
			qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:121
			qw422016.N().S(`_packed
    }
`)
//line templates/golang/mapping.qtpl:123
		} else {
//line templates/golang/mapping.qtpl:124
			StreamPropertyTo(qw422016, resource, property, false, varName)
//line templates/golang/mapping.qtpl:124
			qw422016.N().S(`        `)
//line templates/golang/mapping.qtpl:125
			qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:125
			qw422016.N().S(`_packed, err := types.ByResourcePropertyType(model.ResourceProperty_`)
//line templates/golang/mapping.qtpl:125
			qw422016.E().S(property.Type.String())
//line templates/golang/mapping.qtpl:125
			qw422016.N().S(`).Pack(`)
//line templates/golang/mapping.qtpl:125
			qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:125
			qw422016.N().S(`_mapped)

        if err != nil {
            panic(err)
        }

        properties["`)
//line templates/golang/mapping.qtpl:131
			qw422016.E().S(property.Name)
//line templates/golang/mapping.qtpl:131
			qw422016.N().S(`"] = `)
//line templates/golang/mapping.qtpl:131
			qw422016.E().S(varName)
//line templates/golang/mapping.qtpl:131
			qw422016.N().S(`_packed
`)
//line templates/golang/mapping.qtpl:132
		}
//line templates/golang/mapping.qtpl:133
	}
//line templates/golang/mapping.qtpl:133
	qw422016.N().S(`    return properties
}

func (m *`)
//line templates/golang/mapping.qtpl:137
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:137
	qw422016.N().S(`Mapper) FromProperties(properties map[string]interface{}) *`)
//line templates/golang/mapping.qtpl:137
	qw422016.E().S(typeName)
//line templates/golang/mapping.qtpl:137
	qw422016.N().S(`  {
    var s = m.New()
`)
//line templates/golang/mapping.qtpl:139
	for _, property := range properties {
//line templates/golang/mapping.qtpl:139
		qw422016.N().S(`    if properties["`)
//line templates/golang/mapping.qtpl:140
		qw422016.E().S(property.Name)
//line templates/golang/mapping.qtpl:140
		qw422016.N().S(`"] != nil {
        `)
//line templates/golang/mapping.qtpl:141
		valueVarName := "var_" + GoName(property.Name)

//line templates/golang/mapping.qtpl:141
		qw422016.N().S(`
        `)
//line templates/golang/mapping.qtpl:142
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:142
		qw422016.N().S(` := properties["`)
//line templates/golang/mapping.qtpl:142
		qw422016.E().S(property.Name)
//line templates/golang/mapping.qtpl:142
		qw422016.N().S(`"]
        `)
//line templates/golang/mapping.qtpl:143
		StreamPreparePropertyFromMapping(qw422016, resource, property, valueVarName, false)
//line templates/golang/mapping.qtpl:143
		qw422016.N().S(`

        s.`)
//line templates/golang/mapping.qtpl:145
		StreamGoName(qw422016, property.Name)
//line templates/golang/mapping.qtpl:145
		qw422016.N().S(` = `)
//line templates/golang/mapping.qtpl:145
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:145
		qw422016.N().S(`_mapped
    }
`)
//line templates/golang/mapping.qtpl:147
	}
//line templates/golang/mapping.qtpl:147
	qw422016.N().S(`    return s
}

`)
//line templates/golang/mapping.qtpl:151
}

//line templates/golang/mapping.qtpl:151
func WriteGenerateResourceMappingBodyCode(qq422016 qtio422016.Writer, pkg string, resource *model.Resource, typeName string, properties []*model.ResourceProperty, resources []*model.Resource) {
//line templates/golang/mapping.qtpl:151
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/golang/mapping.qtpl:151
	StreamGenerateResourceMappingBodyCode(qw422016, pkg, resource, typeName, properties, resources)
//line templates/golang/mapping.qtpl:151
	qt422016.ReleaseWriter(qw422016)
//line templates/golang/mapping.qtpl:151
}

//line templates/golang/mapping.qtpl:151
func GenerateResourceMappingBodyCode(pkg string, resource *model.Resource, typeName string, properties []*model.ResourceProperty, resources []*model.Resource) string {
//line templates/golang/mapping.qtpl:151
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/golang/mapping.qtpl:151
	WriteGenerateResourceMappingBodyCode(qb422016, pkg, resource, typeName, properties, resources)
//line templates/golang/mapping.qtpl:151
	qs422016 := string(qb422016.B)
//line templates/golang/mapping.qtpl:151
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/golang/mapping.qtpl:151
	return qs422016
//line templates/golang/mapping.qtpl:151
}

//line templates/golang/mapping.qtpl:153
func StreamPreparePropertyFromMapping(qw422016 *qt422016.Writer, resource *model.Resource, property *model.ResourceProperty, valueVarName string, insideCollection bool) {
//line templates/golang/mapping.qtpl:154
	if property.Type == model.ResourceProperty_REFERENCE {
//line templates/golang/mapping.qtpl:154
		qw422016.N().S(`        `)
//line templates/golang/mapping.qtpl:155
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:155
		qw422016.N().S(`_mapped := `)
//line templates/golang/mapping.qtpl:155
		StreamGoName(qw422016, property.Reference.Resource)
//line templates/golang/mapping.qtpl:155
		qw422016.N().S(`MapperInstance.FromProperties(`)
//line templates/golang/mapping.qtpl:155
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:155
		qw422016.N().S(`.(map[string]interface{}))
`)
//line templates/golang/mapping.qtpl:156
	} else if property.Type == model.ResourceProperty_MAP {
//line templates/golang/mapping.qtpl:156
		qw422016.N().S(`        `)
//line templates/golang/mapping.qtpl:157
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:157
		qw422016.N().S(`_mapped := make(`)
//line templates/golang/mapping.qtpl:157
		StreamPropPureGoType(qw422016, resource, property, property.Name)
//line templates/golang/mapping.qtpl:157
		qw422016.N().S(`)
        for k, v := range `)
//line templates/golang/mapping.qtpl:158
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:158
		qw422016.N().S(`.(map[string]interface{}) {
            `)
//line templates/golang/mapping.qtpl:159
		subValueVarName := "var_3x"

//line templates/golang/mapping.qtpl:159
		qw422016.N().S(`
            `)
//line templates/golang/mapping.qtpl:160
		qw422016.E().S(subValueVarName)
//line templates/golang/mapping.qtpl:160
		qw422016.N().S(` := v
            `)
//line templates/golang/mapping.qtpl:161
		StreamPreparePropertyFromMapping(qw422016, resource, property.Item, subValueVarName, true)
//line templates/golang/mapping.qtpl:161
		qw422016.N().S(`
            `)
//line templates/golang/mapping.qtpl:162
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:162
		qw422016.N().S(`_mapped[k] = `)
//line templates/golang/mapping.qtpl:162
		qw422016.E().S(subValueVarName)
//line templates/golang/mapping.qtpl:162
		qw422016.N().S(`_mapped
        }
`)
//line templates/golang/mapping.qtpl:164
	} else if property.Type == model.ResourceProperty_LIST {
//line templates/golang/mapping.qtpl:164
		qw422016.N().S(`        `)
//line templates/golang/mapping.qtpl:165
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:165
		qw422016.N().S(`_mapped := []`)
//line templates/golang/mapping.qtpl:165
		StreamPropPureGoType(qw422016, resource, property.Item, property.Name)
//line templates/golang/mapping.qtpl:165
		qw422016.N().S(`{}
        for _, v := range `)
//line templates/golang/mapping.qtpl:166
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:166
		qw422016.N().S(`.([]interface{}) {
            `)
//line templates/golang/mapping.qtpl:167
		subValueVarName := "var_4x"

//line templates/golang/mapping.qtpl:167
		qw422016.N().S(`
            `)
//line templates/golang/mapping.qtpl:168
		qw422016.E().S(subValueVarName)
//line templates/golang/mapping.qtpl:168
		qw422016.N().S(` := v
            `)
//line templates/golang/mapping.qtpl:169
		StreamPreparePropertyFromMapping(qw422016, resource, property.Item, subValueVarName, true)
//line templates/golang/mapping.qtpl:169
		qw422016.N().S(`
            `)
//line templates/golang/mapping.qtpl:170
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:170
		qw422016.N().S(`_mapped = append(`)
//line templates/golang/mapping.qtpl:170
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:170
		qw422016.N().S(`_mapped, `)
//line templates/golang/mapping.qtpl:170
		qw422016.E().S(subValueVarName)
//line templates/golang/mapping.qtpl:170
		qw422016.N().S(`_mapped)
        }
`)
//line templates/golang/mapping.qtpl:172
	} else if property.Type == model.ResourceProperty_ENUM {
//line templates/golang/mapping.qtpl:173
		if isNullable(property) && !insideCollection {
//line templates/golang/mapping.qtpl:173
			qw422016.N().S(`        `)
//line templates/golang/mapping.qtpl:174
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:174
			qw422016.N().S(`_mapped := new(`)
//line templates/golang/mapping.qtpl:174
			StreamPropPureGoType(qw422016, resource, property, property.Name)
//line templates/golang/mapping.qtpl:174
			qw422016.N().S(`)
        *`)
//line templates/golang/mapping.qtpl:175
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:175
			qw422016.N().S(`_mapped = (`)
//line templates/golang/mapping.qtpl:175
			StreamPropPureGoType(qw422016, resource, property, property.Name)
//line templates/golang/mapping.qtpl:175
			qw422016.N().S(`)(`)
//line templates/golang/mapping.qtpl:175
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:175
			qw422016.N().S(`.(string))
`)
//line templates/golang/mapping.qtpl:176
		} else {
//line templates/golang/mapping.qtpl:176
			qw422016.N().S(`        `)
//line templates/golang/mapping.qtpl:177
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:177
			qw422016.N().S(`_mapped := (`)
//line templates/golang/mapping.qtpl:177
			StreamPropPureGoType(qw422016, resource, property, property.Name)
//line templates/golang/mapping.qtpl:177
			qw422016.N().S(`)(`)
//line templates/golang/mapping.qtpl:177
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:177
			qw422016.N().S(`.(string))
`)
//line templates/golang/mapping.qtpl:178
		}
//line templates/golang/mapping.qtpl:179
	} else if property.Type == model.ResourceProperty_STRUCT {
//line templates/golang/mapping.qtpl:179
		qw422016.N().S(`        var mappedValue = `)
//line templates/golang/mapping.qtpl:180
		StreamGoName(qw422016, getSubTypeNameByProperty(resource, property))
//line templates/golang/mapping.qtpl:180
		qw422016.N().S(`MapperInstance.FromProperties(`)
//line templates/golang/mapping.qtpl:180
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:180
		qw422016.N().S(`.(map[string]interface{}))
        `)
//line templates/golang/mapping.qtpl:181
		if property.Required || insideCollection {
//line templates/golang/mapping.qtpl:181
			qw422016.N().S(`
        `)
//line templates/golang/mapping.qtpl:182
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:182
			qw422016.N().S(`_mapped := *mappedValue
        `)
//line templates/golang/mapping.qtpl:183
		} else {
//line templates/golang/mapping.qtpl:183
			qw422016.N().S(`
        `)
//line templates/golang/mapping.qtpl:184
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:184
			qw422016.N().S(`_mapped := mappedValue
        `)
//line templates/golang/mapping.qtpl:185
		}
//line templates/golang/mapping.qtpl:185
		qw422016.N().S(`
`)
//line templates/golang/mapping.qtpl:186
	} else if property.Type == model.ResourceProperty_OBJECT {
//line templates/golang/mapping.qtpl:187
		if isNullable(property) && !insideCollection {
//line templates/golang/mapping.qtpl:187
			qw422016.N().S(`            `)
//line templates/golang/mapping.qtpl:188
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:188
			qw422016.N().S(`_mapped := new(interface{})
            *`)
//line templates/golang/mapping.qtpl:189
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:189
			qw422016.N().S(`_mapped = `)
//line templates/golang/mapping.qtpl:189
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:189
			qw422016.N().S(`
`)
//line templates/golang/mapping.qtpl:190
		} else {
//line templates/golang/mapping.qtpl:190
			qw422016.N().S(`            `)
//line templates/golang/mapping.qtpl:191
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:191
			qw422016.N().S(`_mapped := `)
//line templates/golang/mapping.qtpl:191
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:191
			qw422016.N().S(`
`)
//line templates/golang/mapping.qtpl:192
		}
//line templates/golang/mapping.qtpl:193
	} else {
//line templates/golang/mapping.qtpl:193
		qw422016.N().S(`        val, err := types.ByResourcePropertyType(model.ResourceProperty_`)
//line templates/golang/mapping.qtpl:194
		qw422016.E().S(property.Type.String())
//line templates/golang/mapping.qtpl:194
		qw422016.N().S(`).UnPack(`)
//line templates/golang/mapping.qtpl:194
		qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:194
		qw422016.N().S(`)

        if err != nil {
            panic(err)
        }

`)
//line templates/golang/mapping.qtpl:200
		if isNullable(property) && !insideCollection {
//line templates/golang/mapping.qtpl:200
			qw422016.N().S(`        `)
//line templates/golang/mapping.qtpl:201
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:201
			qw422016.N().S(`_mapped := new(`)
//line templates/golang/mapping.qtpl:201
			StreamPropPureGoType(qw422016, resource, property, property.Name)
//line templates/golang/mapping.qtpl:201
			qw422016.N().S(`)
        *`)
//line templates/golang/mapping.qtpl:202
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:202
			qw422016.N().S(`_mapped = val.(`)
//line templates/golang/mapping.qtpl:202
			StreamPropPureGoType(qw422016, resource, property, property.Name)
//line templates/golang/mapping.qtpl:202
			qw422016.N().S(`)
`)
//line templates/golang/mapping.qtpl:203
		} else {
//line templates/golang/mapping.qtpl:203
			qw422016.N().S(`        `)
//line templates/golang/mapping.qtpl:204
			qw422016.E().S(valueVarName)
//line templates/golang/mapping.qtpl:204
			qw422016.N().S(`_mapped := val.(`)
//line templates/golang/mapping.qtpl:204
			StreamPropPureGoType(qw422016, resource, property, property.Name)
//line templates/golang/mapping.qtpl:204
			qw422016.N().S(`)
`)
//line templates/golang/mapping.qtpl:205
		}
//line templates/golang/mapping.qtpl:206
	}
//line templates/golang/mapping.qtpl:207
}

//line templates/golang/mapping.qtpl:207
func WritePreparePropertyFromMapping(qq422016 qtio422016.Writer, resource *model.Resource, property *model.ResourceProperty, valueVarName string, insideCollection bool) {
//line templates/golang/mapping.qtpl:207
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/golang/mapping.qtpl:207
	StreamPreparePropertyFromMapping(qw422016, resource, property, valueVarName, insideCollection)
//line templates/golang/mapping.qtpl:207
	qt422016.ReleaseWriter(qw422016)
//line templates/golang/mapping.qtpl:207
}

//line templates/golang/mapping.qtpl:207
func PreparePropertyFromMapping(resource *model.Resource, property *model.ResourceProperty, valueVarName string, insideCollection bool) string {
//line templates/golang/mapping.qtpl:207
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/golang/mapping.qtpl:207
	WritePreparePropertyFromMapping(qb422016, resource, property, valueVarName, insideCollection)
//line templates/golang/mapping.qtpl:207
	qs422016 := string(qb422016.B)
//line templates/golang/mapping.qtpl:207
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/golang/mapping.qtpl:207
	return qs422016
//line templates/golang/mapping.qtpl:207
}
