// Code generated by qtc from "mapping-new.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/golang/mapping-new.qtpl:1
package golang

//line templates/golang/mapping-new.qtpl:1
import "github.com/apibrew/apibrew/pkg/model"

//line templates/golang/mapping-new.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/golang/mapping-new.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/golang/mapping-new.qtpl:3
func StreamUPropertyTo(qw422016 *qt422016.Writer, resource *model.Resource, property *model.ResourceProperty, isCollectionItem bool, varName string) {
//line templates/golang/mapping-new.qtpl:3
	qw422016.N().S(`    var `)
//line templates/golang/mapping-new.qtpl:4
	qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:4
	qw422016.N().S(`_mapped interface{}

`)
//line templates/golang/mapping-new.qtpl:6
	if property.Type == model.ResourceProperty_ENUM {
//line templates/golang/mapping-new.qtpl:6
		qw422016.N().S(`         `)
//line templates/golang/mapping-new.qtpl:7
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:7
		qw422016.N().S(`_mapped = string(`)
//line templates/golang/mapping-new.qtpl:7
		StreamNormalizePointer(qw422016, property, varName, isCollectionItem, false)
//line templates/golang/mapping-new.qtpl:7
		qw422016.N().S(`)
`)
//line templates/golang/mapping-new.qtpl:8
	} else if property.Type == model.ResourceProperty_UUID {
//line templates/golang/mapping-new.qtpl:8
		qw422016.N().S(`            `)
//line templates/golang/mapping-new.qtpl:9
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:9
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping-new.qtpl:9
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:9
		qw422016.N().S(`.String()
`)
//line templates/golang/mapping-new.qtpl:10
	} else if property.Type == model.ResourceProperty_STRUCT {
//line templates/golang/mapping-new.qtpl:10
		qw422016.N().S(`            `)
//line templates/golang/mapping-new.qtpl:11
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:11
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping-new.qtpl:11
		StreamGoName(qw422016, getSubTypeNameByProperty(resource, property))
//line templates/golang/mapping-new.qtpl:11
		qw422016.N().S(`MapperInstance.ToUnstructured(`)
//line templates/golang/mapping-new.qtpl:11
		StreamNormalizePointer(qw422016, property, varName, isCollectionItem, true)
//line templates/golang/mapping-new.qtpl:11
		qw422016.N().S(`)
`)
//line templates/golang/mapping-new.qtpl:12
	} else if property.Type == model.ResourceProperty_MAP {
//line templates/golang/mapping-new.qtpl:12
		qw422016.N().S(`        var `)
//line templates/golang/mapping-new.qtpl:13
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:13
		qw422016.N().S(`_st map[string]interface{} = make(map[string]interface{})
        for key, value := range `)
//line templates/golang/mapping-new.qtpl:14
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:14
		qw422016.N().S(` {
            `)
//line templates/golang/mapping-new.qtpl:15
		subVarName := "var_1x"

//line templates/golang/mapping-new.qtpl:15
		qw422016.N().S(`
            `)
//line templates/golang/mapping-new.qtpl:16
		qw422016.E().S(subVarName)
//line templates/golang/mapping-new.qtpl:16
		qw422016.N().S(` := value
            `)
//line templates/golang/mapping-new.qtpl:17
		StreamUPropertyTo(qw422016, resource, property.Item, true, subVarName)
//line templates/golang/mapping-new.qtpl:17
		qw422016.N().S(`
            `)
//line templates/golang/mapping-new.qtpl:18
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:18
		qw422016.N().S(`_st[key] = `)
//line templates/golang/mapping-new.qtpl:18
		qw422016.E().S(subVarName)
//line templates/golang/mapping-new.qtpl:18
		qw422016.N().S(`_mapped
        }
        `)
//line templates/golang/mapping-new.qtpl:20
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:20
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping-new.qtpl:20
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:20
		qw422016.N().S(`_st
`)
//line templates/golang/mapping-new.qtpl:21
	} else if property.Type == model.ResourceProperty_LIST {
//line templates/golang/mapping-new.qtpl:21
		qw422016.N().S(`        var `)
//line templates/golang/mapping-new.qtpl:22
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:22
		qw422016.N().S(`_l []interface{}
        for _, value := range `)
//line templates/golang/mapping-new.qtpl:23
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:23
		qw422016.N().S(` {
            `)
//line templates/golang/mapping-new.qtpl:24
		subVarName := "var_5x"

//line templates/golang/mapping-new.qtpl:24
		qw422016.N().S(`
            `)
//line templates/golang/mapping-new.qtpl:25
		qw422016.E().S(subVarName)
//line templates/golang/mapping-new.qtpl:25
		qw422016.N().S(` := value
            `)
//line templates/golang/mapping-new.qtpl:26
		StreamUPropertyTo(qw422016, resource, property.Item, true, subVarName)
//line templates/golang/mapping-new.qtpl:26
		qw422016.N().S(`
            `)
//line templates/golang/mapping-new.qtpl:27
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:27
		qw422016.N().S(`_l = append(`)
//line templates/golang/mapping-new.qtpl:27
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:27
		qw422016.N().S(`_l, `)
//line templates/golang/mapping-new.qtpl:27
		qw422016.E().S(subVarName)
//line templates/golang/mapping-new.qtpl:27
		qw422016.N().S(`_mapped)
        }
        `)
//line templates/golang/mapping-new.qtpl:29
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:29
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping-new.qtpl:29
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:29
		qw422016.N().S(`_l
`)
//line templates/golang/mapping-new.qtpl:30
	} else if property.Type == model.ResourceProperty_REFERENCE {
//line templates/golang/mapping-new.qtpl:30
		qw422016.N().S(`        `)
//line templates/golang/mapping-new.qtpl:31
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:31
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping-new.qtpl:31
		StreamGoName(qw422016, property.Reference.Resource)
//line templates/golang/mapping-new.qtpl:31
		qw422016.N().S(`MapperInstance.ToUnstructured(`)
//line templates/golang/mapping-new.qtpl:31
		StreamNormalizePointer(qw422016, property, varName, isCollectionItem, true)
//line templates/golang/mapping-new.qtpl:31
		qw422016.N().S(`)
`)
//line templates/golang/mapping-new.qtpl:32
	} else {
//line templates/golang/mapping-new.qtpl:32
		qw422016.N().S(`        `)
//line templates/golang/mapping-new.qtpl:33
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:33
		qw422016.N().S(`_mapped = `)
//line templates/golang/mapping-new.qtpl:33
		StreamNormalizePointer(qw422016, property, varName, isCollectionItem, false)
//line templates/golang/mapping-new.qtpl:33
		qw422016.N().S(`
`)
//line templates/golang/mapping-new.qtpl:34
	}
//line templates/golang/mapping-new.qtpl:35
}

//line templates/golang/mapping-new.qtpl:35
func WriteUPropertyTo(qq422016 qtio422016.Writer, resource *model.Resource, property *model.ResourceProperty, isCollectionItem bool, varName string) {
//line templates/golang/mapping-new.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/golang/mapping-new.qtpl:35
	StreamUPropertyTo(qw422016, resource, property, isCollectionItem, varName)
//line templates/golang/mapping-new.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line templates/golang/mapping-new.qtpl:35
}

//line templates/golang/mapping-new.qtpl:35
func UPropertyTo(resource *model.Resource, property *model.ResourceProperty, isCollectionItem bool, varName string) string {
//line templates/golang/mapping-new.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/golang/mapping-new.qtpl:35
	WriteUPropertyTo(qb422016, resource, property, isCollectionItem, varName)
//line templates/golang/mapping-new.qtpl:35
	qs422016 := string(qb422016.B)
//line templates/golang/mapping-new.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/golang/mapping-new.qtpl:35
	return qs422016
//line templates/golang/mapping-new.qtpl:35
}

//line templates/golang/mapping-new.qtpl:37
func StreamUGenerateResourceMappingBodyCode(qw422016 *qt422016.Writer, pkg string, resource *model.Resource, typeName string, properties []*model.ResourceProperty, resources []*model.Resource) {
//line templates/golang/mapping-new.qtpl:37
	qw422016.N().S(`func (m *`)
//line templates/golang/mapping-new.qtpl:38
	qw422016.E().S(typeName)
//line templates/golang/mapping-new.qtpl:38
	qw422016.N().S(`Mapper) ToUnstructured(`)
//line templates/golang/mapping-new.qtpl:38
	StreamGoVarName(qw422016, typeName)
//line templates/golang/mapping-new.qtpl:38
	qw422016.N().S(` *`)
//line templates/golang/mapping-new.qtpl:38
	qw422016.E().S(typeName)
//line templates/golang/mapping-new.qtpl:38
	qw422016.N().S(`) unstructured.Unstructured {
    var properties unstructured.Unstructured = make(unstructured.Unstructured)

`)
//line templates/golang/mapping-new.qtpl:41
	for _, property := range properties {
//line templates/golang/mapping-new.qtpl:41
		qw422016.N().S(`    `)
//line templates/golang/mapping-new.qtpl:42
		varName := "var_" + GoName(property.Name)

//line templates/golang/mapping-new.qtpl:42
		qw422016.N().S(`
    `)
//line templates/golang/mapping-new.qtpl:43
		qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:43
		qw422016.N().S(` := `)
//line templates/golang/mapping-new.qtpl:43
		StreamGoVarName(qw422016, typeName)
//line templates/golang/mapping-new.qtpl:43
		qw422016.N().S(`.`)
//line templates/golang/mapping-new.qtpl:43
		StreamGoName(qw422016, property.Name)
//line templates/golang/mapping-new.qtpl:43
		qw422016.N().S(`

`)
//line templates/golang/mapping-new.qtpl:45
		if isNullable(property) {
//line templates/golang/mapping-new.qtpl:45
			qw422016.N().S(`    if `)
//line templates/golang/mapping-new.qtpl:46
			qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:46
			qw422016.N().S(` != nil {
`)
//line templates/golang/mapping-new.qtpl:47
			StreamUPropertyTo(qw422016, resource, property, false, varName)
//line templates/golang/mapping-new.qtpl:47
			qw422016.N().S(`        properties["`)
//line templates/golang/mapping-new.qtpl:48
			qw422016.E().S(property.Name)
//line templates/golang/mapping-new.qtpl:48
			qw422016.N().S(`"] = `)
//line templates/golang/mapping-new.qtpl:48
			qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:48
			qw422016.N().S(`_mapped
    }
`)
//line templates/golang/mapping-new.qtpl:50
		} else {
//line templates/golang/mapping-new.qtpl:51
			StreamUPropertyTo(qw422016, resource, property, false, varName)
//line templates/golang/mapping-new.qtpl:51
			qw422016.N().S(`        properties["`)
//line templates/golang/mapping-new.qtpl:52
			qw422016.E().S(property.Name)
//line templates/golang/mapping-new.qtpl:52
			qw422016.N().S(`"] = `)
//line templates/golang/mapping-new.qtpl:52
			qw422016.E().S(varName)
//line templates/golang/mapping-new.qtpl:52
			qw422016.N().S(`_mapped
`)
//line templates/golang/mapping-new.qtpl:53
		}
//line templates/golang/mapping-new.qtpl:54
	}
//line templates/golang/mapping-new.qtpl:54
	qw422016.N().S(`

    return properties
}

`)
//line templates/golang/mapping-new.qtpl:60
}

//line templates/golang/mapping-new.qtpl:60
func WriteUGenerateResourceMappingBodyCode(qq422016 qtio422016.Writer, pkg string, resource *model.Resource, typeName string, properties []*model.ResourceProperty, resources []*model.Resource) {
//line templates/golang/mapping-new.qtpl:60
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/golang/mapping-new.qtpl:60
	StreamUGenerateResourceMappingBodyCode(qw422016, pkg, resource, typeName, properties, resources)
//line templates/golang/mapping-new.qtpl:60
	qt422016.ReleaseWriter(qw422016)
//line templates/golang/mapping-new.qtpl:60
}

//line templates/golang/mapping-new.qtpl:60
func UGenerateResourceMappingBodyCode(pkg string, resource *model.Resource, typeName string, properties []*model.ResourceProperty, resources []*model.Resource) string {
//line templates/golang/mapping-new.qtpl:60
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/golang/mapping-new.qtpl:60
	WriteUGenerateResourceMappingBodyCode(qb422016, pkg, resource, typeName, properties, resources)
//line templates/golang/mapping-new.qtpl:60
	qs422016 := string(qb422016.B)
//line templates/golang/mapping-new.qtpl:60
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/golang/mapping-new.qtpl:60
	return qs422016
//line templates/golang/mapping-new.qtpl:60
}
