type: resource
name: author
properties:
  - name: name # name property of author
    type: STRING
    length: 255
    unique: true
    required: true
  - name: description # description property of author
    type: STRING
    length: 255
    unique: true
    required: true
---
type: resource
name: book
properties:
  - name: name # name property of book
    type: STRING
    length: 255
    unique: true
    required: true
  - name: description # description property of book
    type: STRING
    length: 255
    unique: true
    required: true
  - name: author # author property of book, it is referenced to author
    type: REFERENCE
    reference:
      referencedResource: author # reference to author
  - name: isbn # isbn property of book
    type: STRING
    length: 255
    unique: true
    required: true