openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Data Handler'
  description: 'Swagger doc file for data handler rest api'
paths:
  /authentication/token:
    post:
      tags:
        - authentication
      summary: Authentication authenticate
      operationId: authenticationToken
      requestBody:
        description: Authenticate and get token
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AuthenticationTokenRequest"
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AuthenticationTokenResponse"
        '405':
          description: Invalid input
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        fields:
          type: array
    AuthenticationTokenRequest:
      required:
        - username
        - password
      type: object
      properties:
        username:
          type: string
          example: admin
        password:
          type: string
          example: admin
        term:
          type: number
          example: 2
    AuthenticationTokenResponse:
      type: object
      properties:
        token:
          type: object
          properties:
            content:
              type: string
            expiration:
              type: string
              format: date
            term:
              type: number
              example: 2
        error:
          $ref: '#/components/schemas/Error'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [ ]