GET http://localhost:9009/author

###
POST http://localhost:9009/records/default/author
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tL3Rpc2xpYi9kYXRhLWhhbmRsZXIiLCJzdWIiOiJhZG1pbiIsImF1ZCI6WyJnaXRodWIuY29tL3Rpc2xpYi9kYXRhLWhhbmRsZXIiXSwiZXhwIjoxNzM5MDEwNDM1LCJuYmYiOjE2NzU5Mzg0MzUsImlhdCI6MTY3NTkzODQzNSwianRpIjoiZTJiMTZhMmYtY2M1Mi00MWIwLTk4MjktNzIyMTEyNDFkZTg3Iiwic2VjdXJpdHlDb250ZXh0Ijp7ImNvbnN0cmFpbnRzIjpbeyJiZWZvcmUiOnt9LCJhZnRlciI6e30sIm9wZXJhdGlvbiI6NH1dfSwidXNlcm5hbWUiOiJhZG1pbiJ9.zgK_JAP1hfhPmO4uNkT5rl8DxkaOc2UXzXWsQOqAeacgZ2UifPtsJ4xtiSWUXXTz0GXMWJ9CusvbKvWrXZd1UFaEx-EzoL99RRy1OazJsVvwbvn2m8c0aVwE85-OLbhR6Lk5zE4_f4nl58ZTPZaoasc9jd8Y0jDrAUnOj_k9ZVA

{
  "properties": {
    "name": "Taleh",
    "description": "Fake Writer"
  }
}

###
POST http://localhost:9009/records/default/book
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tL3Rpc2xpYi9kYXRhLWhhbmRsZXIiLCJzdWIiOiJhZG1pbiIsImF1ZCI6WyJnaXRodWIuY29tL3Rpc2xpYi9kYXRhLWhhbmRsZXIiXSwiZXhwIjoxNzM5MDEwNDM1LCJuYmYiOjE2NzU5Mzg0MzUsImlhdCI6MTY3NTkzODQzNSwianRpIjoiZTJiMTZhMmYtY2M1Mi00MWIwLTk4MjktNzIyMTEyNDFkZTg3Iiwic2VjdXJpdHlDb250ZXh0Ijp7ImNvbnN0cmFpbnRzIjpbeyJiZWZvcmUiOnt9LCJhZnRlciI6e30sIm9wZXJhdGlvbiI6NH1dfSwidXNlcm5hbWUiOiJhZG1pbiJ9.zgK_JAP1hfhPmO4uNkT5rl8DxkaOc2UXzXWsQOqAeacgZ2UifPtsJ4xtiSWUXXTz0GXMWJ9CusvbKvWrXZd1UFaEx-EzoL99RRy1OazJsVvwbvn2m8c0aVwE85-OLbhR6Lk5zE4_f4nl58ZTPZaoasc9jd8Y0jDrAUnOj_k9ZVA

{
  "properties": {
    "name": "Principles of programming",
    "description": "Fake Writer",
    "author": {
      "name": "Taleh"
    }
  }
}

###
GET http://localhost:9009/records/default/book?resolveReferences=author
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tL3Rpc2xpYi9kYXRhLWhhbmRsZXIiLCJzdWIiOiJhZG1pbiIsImF1ZCI6WyJnaXRodWIuY29tL3Rpc2xpYi9kYXRhLWhhbmRsZXIiXSwiZXhwIjoxNzM5MDEwNDM1LCJuYmYiOjE2NzU5Mzg0MzUsImlhdCI6MTY3NTkzODQzNSwianRpIjoiZTJiMTZhMmYtY2M1Mi00MWIwLTk4MjktNzIyMTEyNDFkZTg3Iiwic2VjdXJpdHlDb250ZXh0Ijp7ImNvbnN0cmFpbnRzIjpbeyJiZWZvcmUiOnt9LCJhZnRlciI6e30sIm9wZXJhdGlvbiI6NH1dfSwidXNlcm5hbWUiOiJhZG1pbiJ9.zgK_JAP1hfhPmO4uNkT5rl8DxkaOc2UXzXWsQOqAeacgZ2UifPtsJ4xtiSWUXXTz0GXMWJ9CusvbKvWrXZd1UFaEx-EzoL99RRy1OazJsVvwbvn2m8c0aVwE85-OLbhR6Lk5zE4_f4nl58ZTPZaoasc9jd8Y0jDrAUnOj_k9ZVA