GET http://localhost:8008/records/default/product
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkYXRhLWhhbmRsZXIiLCJzdWIiOiJhZG1pbiIsImF1ZCI6WyJkYXRhLWhhbmRsZXIiXSwiZXhwIjoxNjc0MTcyOTUwLCJuYmYiOjE2NzQwMDAxNTAsImlhdCI6MTY3NDAwMDE1MCwianRpIjoiZmFhMTY0YTMtNjdlNC00MDZjLWFiODktNzVmMmZiMDQyYzRkIiwic2NvcGVzIjpbInN1cGVyLXVzZXIiXSwidXNlcm5hbWUiOiJhZG1pbiJ9.kdkk7bwYF4rfXaMvakaY-2CUOVqkFjEoaGiU3xLt0plZg1xL23mJPVU96SSCQzcveIua-3FkGnkBgV8u-zET6utoI3FWxnuQhKXwfv68RaovCEbLftemAJTEFd3eajvZvtXe0DcSDfcs_yUK56XD06fD5zyiVY9Hfom7OZuzdtw


#####
