type: system/Namespace
name: nano
---
type: resource
name: Code
namespace:
  name: nano
title: Code
description: Nano code
properties:
  name:
    title: Name
    description: Full Qualified Name of the code, it must be unique in the system
    type: STRING
    length: 255
    immutable: true
    required: true
    unique: true
  language:
    title: Language
    description: Code language
    type: ENUM
    required: true
    enumValues:
      - PYTHON
      - JAVASCRIPT
  content:
    title: Content
    description: Code content
    type: STRING
    length: 64000
    required: true
    annotations:
      SQLType: "TEXT"
  contentFormat:
    title: Content Format
    description: Code content format
    type: ENUM
    required: true
    enumValues:
      - TEXT
      - TAR
      - TAR_GZ
    defaultValue: TEXT
  annotations:
    type: MAP
    required: false
    item:
      type: STRING
annotations:
  EnableAudit: "true"
  OpenApiGroup: "meta"
