type: system/Namespace
name: nano
---
type: resource
name: Code
namespace:
  name: nano
title: Code
description: Nano code
properties:
  name:
    title: Name
    description: Full Qualified Name of the code, it must be unique in the system
    type: STRING
    length: 255
    immutable: true
    required: true
    unique: true
  language:
    title: Language
    description: Code language
    type: ENUM
    required: true
    enumValues:
      - JAVASCRIPT
      - TYPESCRIPT
    defaultValue: JAVASCRIPT
  content:
    title: Content
    description: Code content
    type: STRING
    length: 64000
    required: true
    annotations:
      SQLType: "TEXT"
  contentFormat:
    title: Content Format
    description: Code content format
    type: ENUM
    required: true
    enumValues:
      - TEXT
      - TAR
      - TAR_GZ
    defaultValue: TEXT
  concurrencyLevel:
    title: Concurrency Level
    description: Concurrency level
    type: INT32
    required: false
    defaultValue: 8
  annotations:
    type: MAP
    required: false
    item:
      type: STRING
annotations:
  EnableAudit: "true"
  OpenApiGroup: "meta"
---
type: resource
name: Script
namespace:
  name: nano
virtual: true
title: Script
description: Nano Script
properties:
  language:
    title: Language
    description: Code language
    type: ENUM
    required: true
    enumValues:
      - JAVASCRIPT
      - TYPESCRIPT
    defaultValue: JAVASCRIPT
  source:
    title: Content
    description: Code content
    type: STRING
    length: 64000
    required: true
    annotations:
      SQLType: "TEXT"
  contentFormat:
    title: Content Format
    description: Code content format
    type: ENUM
    required: true
    enumValues:
      - TEXT
      - TAR
      - TAR_GZ
    defaultValue: TEXT
  annotations:
    type: MAP
    required: false
    item:
      type: STRING
  output:
    title: Output
    description: Output of the script
    type: object
annotations:
  EnableAudit: "true"
  OpenApiGroup: "meta"
---
type: resource
name: Module
namespace:
  name: nano
title: Module
description: Nano function
properties:
  name:
    title: Name
    description: Full Qualified Name of the code, it must be unique in the system
    type: STRING
    length: 255
    immutable: true
    required: true
    unique: true
  language:
    title: Language
    description: Code language
    type: ENUM
    required: true
    enumValues:
      - JAVASCRIPT
      - TYPESCRIPT
    defaultValue: JAVASCRIPT
  source:
    title: Content
    description: Code content
    type: STRING
    length: 64000
    required: true
    annotations:
      SQLType: "TEXT"
  contentFormat:
    title: Content Format
    description: Code content format
    type: ENUM
    required: true
    enumValues:
      - TEXT
      - TAR
      - TAR_GZ
    defaultValue: TEXT
  annotations:
    type: MAP
    required: false
    item:
      type: STRING
annotations:
  EnableAudit: "true"
  OpenApiGroup: "meta"