package main

import (
	"github.com/apibrew/apibrew/pkg/model"
	log "github.com/sirupsen/logrus"
	"google.golang.org/protobuf/encoding/protojson"
)

func main() {
	var responseError = &model.Error{}

	responseData := `{
  "resource": {
    "id": "8ab7faac-feb9-11ed-a331-c6aac64f19b2",
    "name": "FunctionExecution",
    "namespace": "logic",
    "sourceConfig": {
      "dataSource": "default",
      "entity": "function_execution"
    },
    "properties": [
      {
        "id": "8ab8385a-feb9-11ed-a331-c6aac64f19b2",
        "name": "id",
        "type": "UUID",
        "mapping": "id",
        "required": true,
        "primary": true,
        "immutable": true,
        "defaultValue": null,
        "exampleValue": null,
        "annotations": {
          "SpecialProperty": "true"
        }
      },
      {
        "id": "8ab838e6-feb9-11ed-a331-c6aac64f19b2",
        "name": "function",
        "type": "REFERENCE",
        "mapping": "function",
        "required": true,
        "defaultValue": null,
        "exampleValue": null,
        "reference": {
          "resource": "Function"
        }
      },
      {
        "id": "8ab83918-feb9-11ed-a331-c6aac64f19b2",
        "name": "input",
        "type": "OBJECT",
        "mapping": "input",
        "defaultValue": null,
        "exampleValue": null
      },
      {
        "id": "8ab83954-feb9-11ed-a331-c6aac64f19b2",
        "name": "output",
        "type": "OBJECT",
        "mapping": "output",
        "defaultValue": null,
        "exampleValue": null
      },
      {
        "id": "8ab83986-feb9-11ed-a331-c6aac64f19b2",
        "name": "error",
        "type": "OBJECT",
        "mapping": "error",
        "defaultValue": null,
        "exampleValue": null
      },
      {
        "id": "8ab839cc-feb9-11ed-a331-c6aac64f19b2",
        "name": "status",
        "type": "ENUM",
        "mapping": "status",
        "defaultValue": null,
        "exampleValue": null,
        "enumValues": [
          "pending",
          "success",
          "error"
        ]
      },
      {
        "id": "8ab839fe-feb9-11ed-a331-c6aac64f19b2",
        "name": "version",
        "type": "INT32",
        "mapping": "version",
        "required": true,
        "defaultValue": null,
        "exampleValue": null,
        "annotations": {
          "SpecialProperty": "true"
        }
      }
    ],
    "virtual": true,
    "immutable": true,
    "description": "FunctionExecution",
    "auditData": {
      "createdOn": "2023-05-30T07:13:56Z",
      "updatedOn": "2023-06-01T12:53:51Z",
      "createdBy": "system",
      "updatedBy": "system"
    },
    "version": 2,
    "annotations": {
      "NormalizedResource": "true"
    }
  },
  "records": [
    {
      "id": "eae77d1c-1c82-11ee-83a7-c6aac64f19b2",
      "properties": {
        "function": {
          "args": [],
          "engine": {
            "id": "1a328012-ff69-11ed-a56a-c6aac64f19b4",
            "name": "nodejs-engine",
            "version": 1
          },
          "id": "92e22c0e-1aa0-11ee-a80e-c6aac64f19b2",
          "module": {
            "content": "LgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDA3NTUAMDAwMDc2NQAwMDAwMDI0ADAwMDAwMDAwMDAwADE0NDQ3MDIyNjQ2ADAxMTQyNQAgNQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1c3RhcgAwMHRhbGVoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAc3RhZmYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDAwMDAwADAwMDAwMDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmdW5jdGlvbnMuanMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDAwMDY0NAAwMDAwNzY1ADAwMDAwMjQAMDAwMDAwMDI2MjcAMTQ0NTEzNjEwMTAAMDEzNzA2ACAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHVzdGFyADAwdGFsZWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzdGFmZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDAwMDAAMDAwMDAwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJ1c2Ugc3RyaWN0IjsKdmFyIF9fYXdhaXRlciA9ICh0aGlzICYmIHRoaXMuX19hd2FpdGVyKSB8fCBmdW5jdGlvbiAodGhpc0FyZywgX2FyZ3VtZW50cywgUCwgZ2VuZXJhdG9yKSB7CiAgICBmdW5jdGlvbiBhZG9wdCh2YWx1ZSkgeyByZXR1cm4gdmFsdWUgaW5zdGFuY2VvZiBQID8gdmFsdWUgOiBuZXcgUChmdW5jdGlvbiAocmVzb2x2ZSkgeyByZXNvbHZlKHZhbHVlKTsgfSk7IH0KICAgIHJldHVybiBuZXcgKFAgfHwgKFAgPSBQcm9taXNlKSkoZnVuY3Rpb24gKHJlc29sdmUsIHJlamVjdCkgewogICAgICAgIGZ1bmN0aW9uIGZ1bGZpbGxlZCh2YWx1ZSkgeyB0cnkgeyBzdGVwKGdlbmVyYXRvci5uZXh0KHZhbHVlKSk7IH0gY2F0Y2ggKGUpIHsgcmVqZWN0KGUpOyB9IH0KICAgICAgICBmdW5jdGlvbiByZWplY3RlZCh2YWx1ZSkgeyB0cnkgeyBzdGVwKGdlbmVyYXRvclsidGhyb3ciXSh2YWx1ZSkpOyB9IGNhdGNoIChlKSB7IHJlamVjdChlKTsgfSB9CiAgICAgICAgZnVuY3Rpb24gc3RlcChyZXN1bHQpIHsgcmVzdWx0LmRvbmUgPyByZXNvbHZlKHJlc3VsdC52YWx1ZSkgOiBhZG9wdChyZXN1bHQudmFsdWUpLnRoZW4oZnVsZmlsbGVkLCByZWplY3RlZCk7IH0KICAgICAgICBzdGVwKChnZW5lcmF0b3IgPSBnZW5lcmF0b3IuYXBwbHkodGhpc0FyZywgX2FyZ3VtZW50cyB8fCBbXSkpLm5leHQoKSk7CiAgICB9KTsKfTsKT2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICJfX2VzTW9kdWxlIiwgeyB2YWx1ZTogdHJ1ZSB9KTsKZXhwb3J0cy50ZXN0MiA9IGV4cG9ydHMudGVzdDEgPSB2b2lkIDA7CmNvbnN0IGF4aW9zXzEgPSByZXF1aXJlKCJheGlvcyIpOwpmdW5jdGlvbiB0ZXN0MShwYXJhbXMpIHsKICAgIHJldHVybiBfX2F3YWl0ZXIodGhpcywgdm9pZCAwLCB2b2lkIDAsIGZ1bmN0aW9uKiAoKSB7CiAgICAgICAgY29uc3QgcmVzcG9uc2UgPSB5aWVsZCBheGlvc18xLmRlZmF1bHQuZ2V0KCdodHRwOi8vdGlzc2Vydi5uZXQ6OTAwOS9kb2NzLycpOwogICAgICAgIGNvbnNvbGUubG9nKCdMb2FkaW5nIGF4aW9zICFAISEgMjIyMjInKTsKICAgICAgICByZXR1cm4gJ3Rlc3QxIGxvYWRlZCc7CiAgICB9KTsKfQpleHBvcnRzLnRlc3QxID0gdGVzdDE7CmZ1bmN0aW9uIHRlc3QyKHBhcmFtcykgewogICAgcmV0dXJuIF9fYXdhaXRlcih0aGlzLCB2b2lkIDAsIHZvaWQgMCwgZnVuY3Rpb24qICgpIHsKICAgICAgICBjb25zdCByZXNwb25zZSA9IHlpZWxkIGF4aW9zXzEuZGVmYXVsdC5nZXQoJ2h0dHA6Ly90aXNzZXJ2Lm5ldDo5MDA5L2RvY3MvJyk7CiAgICAgICAgY29uc29sZS5sb2coJ0xvYWRpbmcgYXhpb3MgIUAhISAxMTExMScpOwogICAgICAgIHJldHVybiAndGVzdDIgbG9hZGVkJzsKICAgIH0pOwp9CmV4cG9ydHMudGVzdDIgPSB0ZXN0MjsKLy8jIHNvdXJjZU1hcHBpbmdVUkw9ZnVuY3Rpb25zLmpzLm1hcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZ1bmN0aW9ucy5qcy5tYXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDAwNjQ0ADAwMDA3NjUAMDAwMDAyNAAwMDAwMDAwMDc2MAAxNDQ1MTM2MTAxMAAwMTQ0NTYAIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdXN0YXIAMDB0YWxlaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHN0YWZmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDAwMDAwMAAwMDAwMDAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeyJ2ZXJzaW9uIjozLCJmaWxlIjoiZnVuY3Rpb25zLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vc3JjL2Z1bmN0aW9ucy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7QUFBQSxpQ0FBeUI7QUFFekIsU0FBc0IsS0FBSyxDQUFDLE1BQU07O1FBQzlCLE1BQU0sUUFBUSxHQUFHLE1BQU0sZUFBSyxDQUFDLEdBQUcsQ0FBQywrQkFBK0IsQ0FBQyxDQUFBO1FBRWpFLE9BQU8sQ0FBQyxHQUFHLENBQUMsMEJBQTBCLENBQUMsQ0FBQTtRQUV2QyxPQUFPLGNBQWMsQ0FBQTtJQUN6QixDQUFDO0NBQUE7QUFORCxzQkFNQztBQUVELFNBQXNCLEtBQUssQ0FBQyxNQUFNOztRQUM5QixNQUFNLFFBQVEsR0FBRyxNQUFNLGVBQUssQ0FBQyxHQUFHLENBQUMsK0JBQStCLENBQUMsQ0FBQTtRQUVqRSxPQUFPLENBQUMsR0FBRyxDQUFDLDBCQUEwQixDQUFDLENBQUE7UUFFdkMsT0FBTyxjQUFjLENBQUE7SUFDekIsQ0FBQztDQUFBO0FBTkQsc0JBTUMifQAAAAAAAAAAAAAAAAAAAABpbmRleC5qcwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDAwMDY0NAAwMDAwNzY1ADAwMDAwMjQAMDAwMDAwMDMwMTcAMTQ0NTEzNjEwMTAAMDEyNzc3ACAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHVzdGFyADAwdGFsZWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzdGFmZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDAwMDAAMDAwMDAwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJ1c2Ugc3RyaWN0IjsKT2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICJfX2VzTW9kdWxlIiwgeyB2YWx1ZTogdHJ1ZSB9KTsKY29uc3QgZnVuY3Rpb25zX2pzXzEgPSByZXF1aXJlKCIuL2Z1bmN0aW9ucy5qcyIpOwpjb25zdCBjbGllbnRfMSA9IHJlcXVpcmUoIkBhcGlicmV3L2NsaWVudCIpOwpjb25zdCBtb2R1bGVfZGVmX2pzXzEgPSByZXF1aXJlKCJAYXBpYnJldy9jbGllbnQvZGlzdC9sb2dpYy9tb2R1bGUtZGVmLmpzIik7CmNsaWVudF8xLkxvZ2ljRGVmLmRlZmluZUZ1bmN0aW9uKCdUZXN0MScsIFtdLCBmdW5jdGlvbnNfanNfMS50ZXN0Mik7CmNsaWVudF8xLkxvZ2ljRGVmLmRlZmluZUZ1bmN0aW9uKCdUZXN0MicsIFtdLCBmdW5jdGlvbnNfanNfMS50ZXN0Mik7CmNsaWVudF8xLkxvZ2ljRGVmLmRlZmluZUZ1bmN0aW9uKCdUZXN0MycsIFsnYScsICdiJ10sICh7IGEsIGIgfSkgPT4gewogICAgcmV0dXJuIGEgKyBiICsgJzMzeHgnOwp9KTsKY2xpZW50XzEuTG9naWNEZWYuZGVmaW5lUmVzb3VyY2UoewogICAgbmFtZTogJ1NpbXBsZUV2ZW50T2JqZWN0JywKICAgIHByb3BlcnRpZXM6IFt7CiAgICAgICAgICAgIG5hbWU6ICdhY3Rpb24nLAogICAgICAgICAgICB0eXBlOiAnRU5VTScsCiAgICAgICAgICAgIGVudW1WYWx1ZXM6IFsKICAgICAgICAgICAgICAgICdBY2NlcHRQYXltZW50JywKICAgICAgICAgICAgICAgICdSZWplY3RQYXltZW50JywKICAgICAgICAgICAgICAgICdDYW5jZWxQYXltZW50JywKICAgICAgICAgICAgICAgICdSZWZ1bmRQYXltZW50JywKICAgICAgICAgICAgXQogICAgICAgIH1dCn0pOwpjbGllbnRfMS5Mb2dpY0RlZi5kZWZpbmVMYW1iZGEoJ1Rlc3RMYW1iZGEnLCAnU2ltcGxlRXZlbnRPYmplY3Q6QWNjZXB0UGF5bWVudCcsIChlbGVtZW50KSA9PiB7CiAgICBjbGllbnRfMS5Mb2dpY0RlZi5maXJlTGFtYmRhKCdTaW1wbGVFdmVudE9iamVjdDpSZWplY3RQYXltZW50Jywge30pOwp9KTsKY2xpZW50XzEuTG9naWNEZWYuZGVmaW5lTGFtYmRhKCdUZXN0TGFtYmRhJywgJ1NpbXBsZUV2ZW50T2JqZWN0OlJlamVjdFBheW1lbnQnLCAoZWxlbWVudCkgPT4gewogICAgY2xpZW50XzEuTG9naWNEZWYuY2FsbEZ1bmN0aW9uKCgwLCBtb2R1bGVfZGVmX2pzXzEuZ2V0TW9kdWxlKSgpLnBhY2thZ2UsICdDYWxsQmFja0ZvckxhbWJkYScsIHsgYTogMSwgYjogMiB9KTsKfSk7CmNsaWVudF8xLkxvZ2ljRGVmLmRlZmluZUZ1bmN0aW9uKCdUcmlnZ2VyTGFtYmRhJywgW10sICh7IGEsIGIgfSkgPT4gewogICAgY2xpZW50XzEuTG9naWNEZWYuZmlyZUxhbWJkYSgnU2ltcGxlRXZlbnRPYmplY3Q6QWNjZXB0UGF5bWVudCcsIHt9KTsKICAgIHJldHVybiAnb2snOwp9KTsKY2xpZW50XzEuTG9naWNEZWYuZGVmaW5lRnVuY3Rpb24oJ0NhbGxCYWNrRm9yTGFtYmRhJywgWydhJywgJ2InXSwgKHsgYSwgYiB9KSA9PiB7CiAgICBjb25zb2xlLmxvZygnQ2FsbEJhY2tGb3JMYW1iZGEgY2FsbGVkJywgYSwgYik7CiAgICByZXR1cm4gJ29rJzsKfSk7Ci8vIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LmpzLm1hcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaW5kZXguanMubWFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDA2NDQAMDAwMDc2NQAwMDAwMDI0ADAwMDAwMDAyNTUxADE0NDUxMzYxMDEwADAxMzU1NQAgMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1c3RhcgAwMHRhbGVoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAc3RhZmYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMDAwMDAwADAwMDAwMDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB7InZlcnNpb24iOjMsImZpbGUiOiJpbmRleC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIi4uL3NyYy9pbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOztBQUNBLGlEQUE4QztBQUM5Qyw0Q0FBMkM7QUFDM0MsNEVBQXFFO0FBRXJFLGlCQUFRLENBQUMsY0FBYyxDQUFDLE9BQU8sRUFBRSxFQUFFLEVBQUUsb0JBQUssQ0FBQyxDQUFBO0FBRTNDLGlCQUFRLENBQUMsY0FBYyxDQUFDLE9BQU8sRUFBRSxFQUFFLEVBQUUsb0JBQUssQ0FBQyxDQUFBO0FBRTNDLGlCQUFRLENBQUMsY0FBYyxDQUFDLE9BQU8sRUFBRSxDQUFDLEdBQUcsRUFBRSxHQUFHLENBQUMsRUFBRSxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsRUFBRSxFQUFFLEVBQUU7SUFDdEQsT0FBTyxDQUFDLEdBQUcsQ0FBQyxHQUFHLE1BQU0sQ0FBQTtBQUN6QixDQUFDLENBQUMsQ0FBQTtBQUVGLGlCQUFRLENBQUMsY0FBYyxDQUFDO0lBQ3BCLElBQUksRUFBRSxtQkFBbUI7SUFDekIsVUFBVSxFQUFFLENBQUM7WUFDVCxJQUFJLEVBQUUsUUFBUTtZQUNkLElBQUksRUFBRSxNQUFNO1lBQ1osVUFBVSxFQUFFO2dCQUNSLGVBQWU7Z0JBQ2YsZUFBZTtnQkFDZixlQUFlO2dCQUNmLGVBQWU7YUFDWDtTQUNYLENBQUM7Q0FDTCxDQUFDLENBQUE7QUFFRixpQkFBUSxDQUFDLFlBQVksQ0FBQyxZQUFZLEVBQUUsaUNBQWlDLEVBQUUsQ0FBQyxPQUFPLEVBQUUsRUFBRTtJQUMvRSxpQkFBUSxDQUFDLFVBQVUsQ0FBQyxpQ0FBaUMsRUFBRSxFQUFFLENBQUMsQ0FBQTtBQUM5RCxDQUFDLENBQUMsQ0FBQTtBQUVGLGlCQUFRLENBQUMsWUFBWSxDQUFDLFlBQVksRUFBRSxpQ0FBaUMsRUFBRSxDQUFDLE9BQU8sRUFBRSxFQUFFO0lBQy9FLGlCQUFRLENBQUMsWUFBWSxDQUFDLElBQUEseUJBQVMsR0FBRSxDQUFDLE9BQU8sRUFBRSxtQkFBbUIsRUFBRSxFQUFFLENBQUMsRUFBRSxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsRUFBRSxDQUFDLENBQUE7QUFDbkYsQ0FBQyxDQUFDLENBQUE7QUFFRixpQkFBUSxDQUFDLGNBQWMsQ0FBQyxlQUFlLEVBQUUsRUFBRSxFQUFFLENBQUMsRUFBRSxDQUFDLEVBQUUsQ0FBQyxFQUFFLEVBQUUsRUFBRTtJQUV0RCxpQkFBUSxDQUFDLFVBQVUsQ0FBQyxpQ0FBaUMsRUFBRSxFQUFFLENBQUMsQ0FBQTtJQUUxRCxPQUFPLElBQUksQ0FBQTtBQUNmLENBQUMsQ0FBQyxDQUFBO0FBRUYsaUJBQVEsQ0FBQyxjQUFjLENBQUMsbUJBQW1CLEVBQUUsQ0FBQyxHQUFHLEVBQUUsR0FBRyxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsRUFBRSxDQUFDLEVBQUUsRUFBRSxFQUFFO0lBRWxFLE9BQU8sQ0FBQyxHQUFHLENBQUMsMEJBQTBCLEVBQUUsQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFBO0lBRTdDLE9BQU8sSUFBSSxDQUFBO0FBQ2YsQ0FBQyxDQUFDLENBQUEifQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpbmRleDIuanMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDAwMDY0NAAwMDAwNzY1ADAwMDAwMjQAMDAwMDAwMDE3NzIAMTQ0NDcxNDM2NDcAMDEzMTEyACAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHVzdGFyADAwdGFsZWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzdGFmZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDAwMDAAMDAwMDAwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJ1c2Ugc3RyaWN0IjsKdmFyIF9fYXdhaXRlciA9ICh0aGlzICYmIHRoaXMuX19hd2FpdGVyKSB8fCBmdW5jdGlvbiAodGhpc0FyZywgX2FyZ3VtZW50cywgUCwgZ2VuZXJhdG9yKSB7CiAgICBmdW5jdGlvbiBhZG9wdCh2YWx1ZSkgeyByZXR1cm4gdmFsdWUgaW5zdGFuY2VvZiBQID8gdmFsdWUgOiBuZXcgUChmdW5jdGlvbiAocmVzb2x2ZSkgeyByZXNvbHZlKHZhbHVlKTsgfSk7IH0KICAgIHJldHVybiBuZXcgKFAgfHwgKFAgPSBQcm9taXNlKSkoZnVuY3Rpb24gKHJlc29sdmUsIHJlamVjdCkgewogICAgICAgIGZ1bmN0aW9uIGZ1bGZpbGxlZCh2YWx1ZSkgeyB0cnkgeyBzdGVwKGdlbmVyYXRvci5uZXh0KHZhbHVlKSk7IH0gY2F0Y2ggKGUpIHsgcmVqZWN0KGUpOyB9IH0KICAgICAgICBmdW5jdGlvbiByZWplY3RlZCh2YWx1ZSkgeyB0cnkgeyBzdGVwKGdlbmVyYXRvclsidGhyb3ciXSh2YWx1ZSkpOyB9IGNhdGNoIChlKSB7IHJlamVjdChlKTsgfSB9CiAgICAgICAgZnVuY3Rpb24gc3RlcChyZXN1bHQpIHsgcmVzdWx0LmRvbmUgPyByZXNvbHZlKHJlc3VsdC52YWx1ZSkgOiBhZG9wdChyZXN1bHQudmFsdWUpLnRoZW4oZnVsZmlsbGVkLCByZWplY3RlZCk7IH0KICAgICAgICBzdGVwKChnZW5lcmF0b3IgPSBnZW5lcmF0b3IuYXBwbHkodGhpc0FyZywgX2FyZ3VtZW50cyB8fCBbXSkpLm5leHQoKSk7CiAgICB9KTsKfTsKT2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICJfX2VzTW9kdWxlIiwgeyB2YWx1ZTogdHJ1ZSB9KTsKY29uc3QgZnVuY3Rpb25zX2pzXzEgPSByZXF1aXJlKCIuL2Z1bmN0aW9ucy5qcyIpOwpmdW5jdGlvbiBkZWZhdWx0XzEocGFyYW1zKSB7CiAgICByZXR1cm4gX19hd2FpdGVyKHRoaXMsIHZvaWQgMCwgdm9pZCAwLCBmdW5jdGlvbiogKCkgewogICAgICAgIHJldHVybiAoMCwgZnVuY3Rpb25zX2pzXzEudGVzdDEpKHBhcmFtcyk7CiAgICB9KTsKfQpleHBvcnRzLmRlZmF1bHQgPSBkZWZhdWx0XzE7Ci8vIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4Mi5qcy5tYXAAAAAAAABpbmRleDIuanMubWFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDAwMDY0NAAwMDAwNzY1ADAwMDAwMjQAMDAwMDAwMDAzMjYAMTQ0NDcxNDM2NDcAMDEzNjYwACAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHVzdGFyADAwdGFsZWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzdGFmZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDAwMDAAMDAwMDAwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHsidmVyc2lvbiI6MywiZmlsZSI6ImluZGV4Mi5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIi4uL3NyYy9pbmRleDIudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7QUFDQSxpREFBdUM7QUFFdkMsbUJBQStCLE1BQU07O1FBQ2pDLE9BQU8sSUFBQSxvQkFBSyxFQUFDLE1BQU0sQ0FBQyxDQUFBO0lBQ3hCLENBQUM7Q0FBQTtBQUZELDRCQUVDIn0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
            "engine": {
              "id": "1a328012-ff69-11ed-a56a-c6aac64f19b4",
              "name": "nodejs-engine",
              "version": 1
            },
            "id": "a0ff7cce-16ae-11ee-8665-c6aac64f19b2",
            "package": "Test",
            "version": 52
          },
          "name": "TriggerLambda",
          "package": "Test",
          "version": 69
        },
        "id": "eae77d1c-1c82-11ee-83a7-c6aac64f19b2",
        "input": {},
        "version": 1
      }
    }
  ],
  "sync": true,
  "time": "2023-07-07T04:58:30.743379Z"
}`

	err := protojson.Unmarshal([]byte(responseData), responseError)

	if err != nil {
		log.Print(err)
	}
}
