// AUTOGENERATED FILE

//go:build !codeanalysis

package resource_model

import (
	"github.com/apibrew/apibrew/pkg/model"
	"github.com/apibrew/apibrew/pkg/types"
	"google.golang.org/protobuf/types/known/structpb"
)

import "github.com/google/uuid"
import "time"
import "github.com/apibrew/apibrew/pkg/formats/unstructured"

type NamespaceMapper struct {
}

func NewNamespaceMapper() *NamespaceMapper {
	return &NamespaceMapper{}
}

var NamespaceMapperInstance = NewNamespaceMapper()

func (m *NamespaceMapper) New() *Namespace {
	return &Namespace{}
}

func (m *NamespaceMapper) ToRecord(namespace *Namespace) *model.Record {
	var rec = &model.Record{}
	rec.Properties = m.ToProperties(namespace)

	if namespace.Id != nil {
		rec.Id = namespace.Id.String()
	}

	return rec
}

func (m *NamespaceMapper) FromRecord(record *model.Record) *Namespace {
	return m.FromProperties(record.Properties)
}

func (m *NamespaceMapper) ToProperties(namespace *Namespace) map[string]*structpb.Value {
	var properties = make(map[string]*structpb.Value)

	var_456c2ce73085 := namespace.Id

	if var_456c2ce73085 != nil {
		var var_456c2ce73085_mapped *structpb.Value

		var var_456c2ce73085_err error
		var_456c2ce73085_mapped, var_456c2ce73085_err = types.ByResourcePropertyType(model.ResourceProperty_UUID).Pack(*var_456c2ce73085)
		if var_456c2ce73085_err != nil {
			panic(var_456c2ce73085_err)
		}
		properties["id"] = var_456c2ce73085_mapped
	}

	var_eaedc66af734 := namespace.Version

	var var_eaedc66af734_mapped *structpb.Value

	var var_eaedc66af734_err error
	var_eaedc66af734_mapped, var_eaedc66af734_err = types.ByResourcePropertyType(model.ResourceProperty_INT32).Pack(var_eaedc66af734)
	if var_eaedc66af734_err != nil {
		panic(var_eaedc66af734_err)
	}
	properties["version"] = var_eaedc66af734_mapped

	var_84868089005f := namespace.CreatedBy

	if var_84868089005f != nil {
		var var_84868089005f_mapped *structpb.Value

		var var_84868089005f_err error
		var_84868089005f_mapped, var_84868089005f_err = types.ByResourcePropertyType(model.ResourceProperty_STRING).Pack(*var_84868089005f)
		if var_84868089005f_err != nil {
			panic(var_84868089005f_err)
		}
		properties["createdBy"] = var_84868089005f_mapped
	}

	var_bc7c10fd605d := namespace.UpdatedBy

	if var_bc7c10fd605d != nil {
		var var_bc7c10fd605d_mapped *structpb.Value

		var var_bc7c10fd605d_err error
		var_bc7c10fd605d_mapped, var_bc7c10fd605d_err = types.ByResourcePropertyType(model.ResourceProperty_STRING).Pack(*var_bc7c10fd605d)
		if var_bc7c10fd605d_err != nil {
			panic(var_bc7c10fd605d_err)
		}
		properties["updatedBy"] = var_bc7c10fd605d_mapped
	}

	var_45335e752208 := namespace.CreatedOn

	if var_45335e752208 != nil {
		var var_45335e752208_mapped *structpb.Value

		var var_45335e752208_err error
		var_45335e752208_mapped, var_45335e752208_err = types.ByResourcePropertyType(model.ResourceProperty_TIMESTAMP).Pack(*var_45335e752208)
		if var_45335e752208_err != nil {
			panic(var_45335e752208_err)
		}
		properties["createdOn"] = var_45335e752208_mapped
	}

	var_60a5bd57b6d4 := namespace.UpdatedOn

	if var_60a5bd57b6d4 != nil {
		var var_60a5bd57b6d4_mapped *structpb.Value

		var var_60a5bd57b6d4_err error
		var_60a5bd57b6d4_mapped, var_60a5bd57b6d4_err = types.ByResourcePropertyType(model.ResourceProperty_TIMESTAMP).Pack(*var_60a5bd57b6d4)
		if var_60a5bd57b6d4_err != nil {
			panic(var_60a5bd57b6d4_err)
		}
		properties["updatedOn"] = var_60a5bd57b6d4_mapped
	}

	var_86884518779c := namespace.Name

	var var_86884518779c_mapped *structpb.Value

	var var_86884518779c_err error
	var_86884518779c_mapped, var_86884518779c_err = types.ByResourcePropertyType(model.ResourceProperty_STRING).Pack(var_86884518779c)
	if var_86884518779c_err != nil {
		panic(var_86884518779c_err)
	}
	properties["name"] = var_86884518779c_mapped

	var_4cb927df0c94 := namespace.Description

	if var_4cb927df0c94 != nil {
		var var_4cb927df0c94_mapped *structpb.Value

		var var_4cb927df0c94_err error
		var_4cb927df0c94_mapped, var_4cb927df0c94_err = types.ByResourcePropertyType(model.ResourceProperty_STRING).Pack(*var_4cb927df0c94)
		if var_4cb927df0c94_err != nil {
			panic(var_4cb927df0c94_err)
		}
		properties["description"] = var_4cb927df0c94_mapped
	}

	var_d7e50dc3b9c4 := namespace.Details

	if var_d7e50dc3b9c4 != nil {
		var var_d7e50dc3b9c4_mapped *structpb.Value

		var var_d7e50dc3b9c4_err error
		var_d7e50dc3b9c4_mapped, var_d7e50dc3b9c4_err = types.ByResourcePropertyType(model.ResourceProperty_OBJECT).Pack(*var_d7e50dc3b9c4)
		if var_d7e50dc3b9c4_err != nil {
			panic(var_d7e50dc3b9c4_err)
		}
		properties["details"] = var_d7e50dc3b9c4_mapped
	}
	return properties
}

func (m *NamespaceMapper) FromProperties(properties map[string]*structpb.Value) *Namespace {
	var s = m.New()
	if properties["id"] != nil {

		var_1b934368d225 := properties["id"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_UUID).UnPack(var_1b934368d225)

		if err != nil {
			panic(err)
		}

		var_1b934368d225_mapped := new(uuid.UUID)
		*var_1b934368d225_mapped = val.(uuid.UUID)

		s.Id = var_1b934368d225_mapped
	}
	if properties["version"] != nil {

		var_eb0843f66935 := properties["version"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_INT32).UnPack(var_eb0843f66935)

		if err != nil {
			panic(err)
		}

		var_eb0843f66935_mapped := val.(int32)

		s.Version = var_eb0843f66935_mapped
	}
	if properties["createdBy"] != nil {

		var_f971ea922042 := properties["createdBy"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_STRING).UnPack(var_f971ea922042)

		if err != nil {
			panic(err)
		}

		var_f971ea922042_mapped := new(string)
		*var_f971ea922042_mapped = val.(string)

		s.CreatedBy = var_f971ea922042_mapped
	}
	if properties["updatedBy"] != nil {

		var_643569489978 := properties["updatedBy"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_STRING).UnPack(var_643569489978)

		if err != nil {
			panic(err)
		}

		var_643569489978_mapped := new(string)
		*var_643569489978_mapped = val.(string)

		s.UpdatedBy = var_643569489978_mapped
	}
	if properties["createdOn"] != nil {

		var_8b41dd7e2cd2 := properties["createdOn"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_TIMESTAMP).UnPack(var_8b41dd7e2cd2)

		if err != nil {
			panic(err)
		}

		var_8b41dd7e2cd2_mapped := new(time.Time)
		*var_8b41dd7e2cd2_mapped = val.(time.Time)

		s.CreatedOn = var_8b41dd7e2cd2_mapped
	}
	if properties["updatedOn"] != nil {

		var_4407a9583aad := properties["updatedOn"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_TIMESTAMP).UnPack(var_4407a9583aad)

		if err != nil {
			panic(err)
		}

		var_4407a9583aad_mapped := new(time.Time)
		*var_4407a9583aad_mapped = val.(time.Time)

		s.UpdatedOn = var_4407a9583aad_mapped
	}
	if properties["name"] != nil {

		var_e101ce240333 := properties["name"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_STRING).UnPack(var_e101ce240333)

		if err != nil {
			panic(err)
		}

		var_e101ce240333_mapped := val.(string)

		s.Name = var_e101ce240333_mapped
	}
	if properties["description"] != nil {

		var_aa01621075ff := properties["description"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_STRING).UnPack(var_aa01621075ff)

		if err != nil {
			panic(err)
		}

		var_aa01621075ff_mapped := new(string)
		*var_aa01621075ff_mapped = val.(string)

		s.Description = var_aa01621075ff_mapped
	}
	if properties["details"] != nil {

		var_ae0e1f5c64dc := properties["details"]
		var_ae0e1f5c64dc_mapped := new(unstructured.Unstructured)
		*var_ae0e1f5c64dc_mapped = unstructured.FromStructValue(var_ae0e1f5c64dc.GetStructValue())

		s.Details = var_ae0e1f5c64dc_mapped
	}
	return s
}
