POST localhost:9009/records/default/SimpleEventObject
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tL2FwaWJyZXcvYXBpYnJldyIsInN1YiI6ImFkbWluIiwiYXVkIjpbImdpdGh1Yi5jb20vYXBpYnJldy9hcGlicmV3Il0sImV4cCI6MTc1MTU3MDk5MywibmJmIjoxNjg4NDk4OTkzLCJpYXQiOjE2ODg0OTg5OTMsImp0aSI6ImFjYjFhYjc2LTc1YjUtNDgwMS1iM2Q1LTZlNDQzMjgwNzY2NyIsInNlY3VyaXR5Q29uc3RyYWludHMiOlt7Im5hbWVzcGFjZSI6IioiLCJyZXNvdXJjZSI6IioiLCJwcm9wZXJ0eSI6IioiLCJvcGVyYXRpb24iOiJGVUxMIiwicm9sZSI6InJvb3QifV0sInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJyb290Il0sInVpZCI6IjI5MDA1NTY2LWZlYjktMTFlZC1hNGM5LWM2YWFjNjRmMTliMiJ9.prAbptjk4koCpk_M9wO6bm8wiCqHU7wK2MT68c-nT5WMw6KNPiLwke98hNFr1nNPCd-HnATiueW4Vwl1G1V_Hw01Tz6MwZNFtbyqn0HdEpY8G_uHwBfFwWKylfM6TG_hHJfoG8OMndFct6QFhyAOSBI_j_yj96ooYOE1BxtD3Dg
Content-Type: application/json

{
  "action": "AcceptPayment"
}

###

GET localhost:9009/system/resources/system/user
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tL2FwaWJyZXcvYXBpYnJldyIsInN1YiI6ImFkbWluIiwiYXVkIjpbImdpdGh1Yi5jb20vYXBpYnJldy9hcGlicmV3Il0sImV4cCI6MTc1MTU3MDk5MywibmJmIjoxNjg4NDk4OTkzLCJpYXQiOjE2ODg0OTg5OTMsImp0aSI6ImFjYjFhYjc2LTc1YjUtNDgwMS1iM2Q1LTZlNDQzMjgwNzY2NyIsInNlY3VyaXR5Q29uc3RyYWludHMiOlt7Im5hbWVzcGFjZSI6IioiLCJyZXNvdXJjZSI6IioiLCJwcm9wZXJ0eSI6IioiLCJvcGVyYXRpb24iOiJGVUxMIiwicm9sZSI6InJvb3QifV0sInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJyb290Il0sInVpZCI6IjI5MDA1NTY2LWZlYjktMTFlZC1hNGM5LWM2YWFjNjRmMTliMiJ9.prAbptjk4koCpk_M9wO6bm8wiCqHU7wK2MT68c-nT5WMw6KNPiLwke98hNFr1nNPCd-HnATiueW4Vwl1G1V_Hw01Tz6MwZNFtbyqn0HdEpY8G_uHwBfFwWKylfM6TG_hHJfoG8OMndFct6QFhyAOSBI_j_yj96ooYOE1BxtD3Dg

