#!/bin/sh
cd "$(dirname "$0")" || exit

version=`cat ../version`

new_version=`echo $version | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}'`

echo $new_version > ../version

git add ../version
