type: record
resource: Menu
namespace: ui
properties:
  name: main
  children:
    - title: User Pages
      icon: article
      link: pages
      children:
        - title: Country
          link: country
          component: CoreUI/Crud
          params:
            namespace: default
            resource: country
          icon: table_rows
          securityConstraint:
            resource: country
            namespace: default
        - title: City
          link: city
          component: CoreUI/Crud
          params:
            namespace: default
            resource: city
          securityConstraint:
            resource: city
            namespace: default
    - title: Documentation
      icon: description
      link: description
      children:
        - title: SDK
          link: sdk
          icon: api
          component: Documentation/Sdk
          params:
            namespace: system
            resource: user
        - title: System design
          link: system-design
          children:
            - title: Resource Design
              link: resource-design
              component: Documentation/Sdk
              params:
                namespace: system
                resource: user
            - title: Internal Design
              link: internal-design
              component: Documentation/Sdk
              params:
                namespace: system
                resource: user
    - title: User & Management
      icon: admin_panel_settings
      link: user-management
      children:
        - title: User
          link: user
          icon: person
          component: CoreUI/Crud
          params:
            namespace: system
            resource: user
        - title: Role
          icon: lock
          link: role
          component: CoreUI/Crud
          params:
            namespace: system
            resource: role
    - title: Develop
      icon: code
      link: develop
      children:
        - title: Resources
          link: resources
          icon: api
          component: CoreUI/Crud
          params:
            namespace: system
            resource: resource
        - title: Namespaces
          link: namespaces
          icon: api
          component: CoreUI/Crud
          params:
            namespace: system
            resource: namespace
        - title: Logic
          link: logic
          children:
            - title: Function
              link: function
              icon: functions
              component: CoreUI/Crud
              params:
                namespace: logic
                resource: Function
            - title: Trigger
              icon: commit
              link: function-trigger
              component: CoreUI/Crud
              params:
                namespace: logic
                resource: FunctionTrigger
            - title: Rule
              icon: rule
              link: resource-rule
              component: CoreUI/Crud
              params:
                namespace: logic
                resource: ResourceRule
            - title: FunctionExecution
              icon: smart_button
              link: function-execution
              component: CoreUI/Crud
              params:
                namespace: logic
                resource: FunctionExecution
        - title: Advanced
          link: advanced
          children:
          - title: Extensions
            link: extensions
            icon: api
            component: CoreUI/Crud
            params:
              namespace: system
              resource: extension
          - title: Data Sources
            link: data-sources
            icon: api
            component: CoreUI/Crud
            params:
              namespace: system
              resource: data-source