type: resource
name: complex-type-enum
properties:
  - name: name
    type: STRING
    length: 255
    unique: true
    required: true
  - name: status
    type: ENUM
    enumValues:
      - active
      - inactive
      - deleted
      - archived
---
type: resource
name: complex-type-list
properties:
  - name: name
    type: STRING
    length: 255
    unique: true
    required: true
  - name: items
    type: LIST
    Item:
      type: STRING
      length: 255
---
type: resource
name: complex-type-map
properties:
  - name: name
    type: STRING
    length: 255
    unique: true
    required: true
  - name: status
    type: MAP
    Item:
      type: STRING
      length: 255
---
type: resource
name: complex-type-struct
properties:
  - name: name
    type: STRING
    length: 255
    unique: true
    required: true
  - name: status
    type: STRUCT
    properties:
      - name: name
        type: STRING
        length: 255
        unique: true
        required: true
      - name: status
        type: ENUM
        enumValues:
          - active
          - inactive
          - deleted
          - archived