baseURL = 'http://datahandler.talehibrahimli.com/'
languageCode = 'en-us'
title = 'Data Handler'

theme = "hugo-geekdoc"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[params]
    geekdocMenuBundle = true
    geekdocRepo = "https://github.com/tislib/data-handler"
[markup]
    [markup.goldmark.renderer]
# Needed for mermaid shortcode
        unsafe = true
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 9

[taxonomies]
    tag = "tags"