kind: Pod
apiVersion: v1
metadata:
  name: apibrew-standalone
  labels:
    app: apibrew-standalone
spec:
  containers:
    - name: apibrew-standalone
      image: apibrew/apibrew:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 9009
      volumeMounts:
        - name: config
          mountPath: /app/config.json
          subPath: config.json
  volumes:
    - name: config
      configMap:
        name: apibrew-standalone-config
        items:
          - key: config.json
            path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: apibrew-standalone
spec:
  selector:
    app: apibrew-standalone
  ports:
    - protocol: TCP
      port: 9009
      targetPort: 9009
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apibrew-standalone-config
data:
  config.json: |
    {
      "config":  {
        "host":  "0.0.0.0",
        "port":  "9009"
      },
      "systemDataSource":  {
        "id":  "system",
        "name":  "system",
        "backend":  "POSTGRESQL",
        "postgresqlParams":  {
          "username":  "root",
          "password":  "root",
          "host":  "db",
          "port":  5432,
          "dbName":  "dh_system",
          "defaultSchema":  "public"
        },
        "auditData":  null,
        "version":  0
      },
      "systemNamespace":  {
        "name":  "system",
        "auditData":  null,
        "version":  0
      },
      "initDataSources":  [
        {
          "id":  "default",
          "name":  "default",
          "backend":  "POSTGRESQL",
          "postgresqlParams":  {
            "username":  "root",
            "password":  "root",
            "host":  "db",
            "port":  5432,
            "dbName":  "dh_data",
            "defaultSchema":  "public"
          },
          "auditData":  null,
          "version":  0
        }
      ],
      "initNamespaces":  [],
      "initUsers":  [
        {
          "id":  "",
          "username":  "admin",
          "password":  "admin",
          "securityContext":  {
            "constraints": [
              {
                "namespace": "*",
                "resource": "*",
                "operation": "FULL",
                "permit": 0
              }
            ]
          },
          "details":  null,
          "auditData":  null,
          "version":  0
        }
      ],
      "initResources":  [],
      "initRecords":  []
    }
  
  
