type: record
namespace: ui
resource: AppDesignerBoard
properties:
  name: Default
  description: 'The default board.'
  resourceSelector: [ '*' ]
  namespaceSelector: [ 'default' ]
---
type: record
namespace: ui
resource: Crud
properties:
  name: CrudSettings
  namespace: ui
  resource: Crud
  formConfig:
    children:
      - kind: tab
        title: Details
        children:
      - kind: tab
        title: Form Config
        children:
          - kind: property
            propertyPath: formConfig
            children:
              - kind: custom
                component: CrudSettingsFormConfig
      - kind: tab
        title: Grid Config
        children:
          - kind: property
            propertyPath: gridConfig
            children:
              - kind: custom
                component: CrudSettingsGridConfig
      - kind: tab
        title: Advanced
