version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  apibrew:
    restart: always
    image: tislib/apibrew:latest
    volumes:
      - ./config.json:/app/config.json
    ports:
      - 9009:9009
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  apibrew-ui:
    restart: always
    image: tislib/apibrew-ui:latest
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js
    ports:
      - 9080:80