version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  apibrew:
    image: tislib/apibrew:latest
    restart: always
    volumes:
      - ./config.json:/app/config.json
    ports:
      - 9009:9009
    depends_on:
        db:
          condition: service_healthy
    links:
      - db