// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: ext/record.proto

package ext

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RecordExtensionClient is the client API for RecordExtension service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordExtensionClient interface {
	BeforeList(ctx context.Context, in *BeforeListRecordRequest, opts ...grpc.CallOption) (*BeforeListRecordResponse, error)
	List(ctx context.Context, in *ListRecordRequest, opts ...grpc.CallOption) (*ListRecordResponse, error)
	AfterList(ctx context.Context, in *AfterListRecordRequest, opts ...grpc.CallOption) (*AfterListRecordResponse, error)
	BeforeCreate(ctx context.Context, in *BeforeCreateRecordRequest, opts ...grpc.CallOption) (*BeforeCreateRecordResponse, error)
	Create(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*CreateRecordResponse, error)
	AfterCreate(ctx context.Context, in *AfterCreateRecordRequest, opts ...grpc.CallOption) (*AfterCreateRecordResponse, error)
	BeforeUpdate(ctx context.Context, in *BeforeUpdateRecordRequest, opts ...grpc.CallOption) (*BeforeUpdateRecordResponse, error)
	Update(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordResponse, error)
	AfterUpdate(ctx context.Context, in *AfterUpdateRecordRequest, opts ...grpc.CallOption) (*AfterUpdateRecordResponse, error)
	BeforeDelete(ctx context.Context, in *BeforeDeleteRecordRequest, opts ...grpc.CallOption) (*BeforeDeleteRecordResponse, error)
	Delete(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error)
	AfterDelete(ctx context.Context, in *AfterDeleteRecordRequest, opts ...grpc.CallOption) (*AfterDeleteRecordResponse, error)
	BeforeGet(ctx context.Context, in *BeforeGetRecordRequest, opts ...grpc.CallOption) (*BeforeGetRecordResponse, error)
	Get(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error)
	AfterGet(ctx context.Context, in *AfterGetRecordRequest, opts ...grpc.CallOption) (*AfterGetRecordResponse, error)
}

type recordExtensionClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordExtensionClient(cc grpc.ClientConnInterface) RecordExtensionClient {
	return &recordExtensionClient{cc}
}

func (c *recordExtensionClient) BeforeList(ctx context.Context, in *BeforeListRecordRequest, opts ...grpc.CallOption) (*BeforeListRecordResponse, error) {
	out := new(BeforeListRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/BeforeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) List(ctx context.Context, in *ListRecordRequest, opts ...grpc.CallOption) (*ListRecordResponse, error) {
	out := new(ListRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) AfterList(ctx context.Context, in *AfterListRecordRequest, opts ...grpc.CallOption) (*AfterListRecordResponse, error) {
	out := new(AfterListRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/AfterList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) BeforeCreate(ctx context.Context, in *BeforeCreateRecordRequest, opts ...grpc.CallOption) (*BeforeCreateRecordResponse, error) {
	out := new(BeforeCreateRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/BeforeCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) Create(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*CreateRecordResponse, error) {
	out := new(CreateRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) AfterCreate(ctx context.Context, in *AfterCreateRecordRequest, opts ...grpc.CallOption) (*AfterCreateRecordResponse, error) {
	out := new(AfterCreateRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/AfterCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) BeforeUpdate(ctx context.Context, in *BeforeUpdateRecordRequest, opts ...grpc.CallOption) (*BeforeUpdateRecordResponse, error) {
	out := new(BeforeUpdateRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/BeforeUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) Update(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordResponse, error) {
	out := new(UpdateRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) AfterUpdate(ctx context.Context, in *AfterUpdateRecordRequest, opts ...grpc.CallOption) (*AfterUpdateRecordResponse, error) {
	out := new(AfterUpdateRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/AfterUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) BeforeDelete(ctx context.Context, in *BeforeDeleteRecordRequest, opts ...grpc.CallOption) (*BeforeDeleteRecordResponse, error) {
	out := new(BeforeDeleteRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/BeforeDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) Delete(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error) {
	out := new(DeleteRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) AfterDelete(ctx context.Context, in *AfterDeleteRecordRequest, opts ...grpc.CallOption) (*AfterDeleteRecordResponse, error) {
	out := new(AfterDeleteRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/AfterDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) BeforeGet(ctx context.Context, in *BeforeGetRecordRequest, opts ...grpc.CallOption) (*BeforeGetRecordResponse, error) {
	out := new(BeforeGetRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/BeforeGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) Get(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error) {
	out := new(GetRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordExtensionClient) AfterGet(ctx context.Context, in *AfterGetRecordRequest, opts ...grpc.CallOption) (*AfterGetRecordResponse, error) {
	out := new(AfterGetRecordResponse)
	err := c.cc.Invoke(ctx, "/ext.RecordExtension/AfterGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordExtensionServer is the server API for RecordExtension service.
// All implementations must embed UnimplementedRecordExtensionServer
// for forward compatibility
type RecordExtensionServer interface {
	BeforeList(context.Context, *BeforeListRecordRequest) (*BeforeListRecordResponse, error)
	List(context.Context, *ListRecordRequest) (*ListRecordResponse, error)
	AfterList(context.Context, *AfterListRecordRequest) (*AfterListRecordResponse, error)
	BeforeCreate(context.Context, *BeforeCreateRecordRequest) (*BeforeCreateRecordResponse, error)
	Create(context.Context, *CreateRecordRequest) (*CreateRecordResponse, error)
	AfterCreate(context.Context, *AfterCreateRecordRequest) (*AfterCreateRecordResponse, error)
	BeforeUpdate(context.Context, *BeforeUpdateRecordRequest) (*BeforeUpdateRecordResponse, error)
	Update(context.Context, *UpdateRecordRequest) (*UpdateRecordResponse, error)
	AfterUpdate(context.Context, *AfterUpdateRecordRequest) (*AfterUpdateRecordResponse, error)
	BeforeDelete(context.Context, *BeforeDeleteRecordRequest) (*BeforeDeleteRecordResponse, error)
	Delete(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error)
	AfterDelete(context.Context, *AfterDeleteRecordRequest) (*AfterDeleteRecordResponse, error)
	BeforeGet(context.Context, *BeforeGetRecordRequest) (*BeforeGetRecordResponse, error)
	Get(context.Context, *GetRecordRequest) (*GetRecordResponse, error)
	AfterGet(context.Context, *AfterGetRecordRequest) (*AfterGetRecordResponse, error)
	mustEmbedUnimplementedRecordExtensionServer()
}

// UnimplementedRecordExtensionServer must be embedded to have forward compatible implementations.
type UnimplementedRecordExtensionServer struct {
}

func (UnimplementedRecordExtensionServer) BeforeList(context.Context, *BeforeListRecordRequest) (*BeforeListRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeforeList not implemented")
}
func (UnimplementedRecordExtensionServer) List(context.Context, *ListRecordRequest) (*ListRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRecordExtensionServer) AfterList(context.Context, *AfterListRecordRequest) (*AfterListRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AfterList not implemented")
}
func (UnimplementedRecordExtensionServer) BeforeCreate(context.Context, *BeforeCreateRecordRequest) (*BeforeCreateRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeforeCreate not implemented")
}
func (UnimplementedRecordExtensionServer) Create(context.Context, *CreateRecordRequest) (*CreateRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRecordExtensionServer) AfterCreate(context.Context, *AfterCreateRecordRequest) (*AfterCreateRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AfterCreate not implemented")
}
func (UnimplementedRecordExtensionServer) BeforeUpdate(context.Context, *BeforeUpdateRecordRequest) (*BeforeUpdateRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeforeUpdate not implemented")
}
func (UnimplementedRecordExtensionServer) Update(context.Context, *UpdateRecordRequest) (*UpdateRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRecordExtensionServer) AfterUpdate(context.Context, *AfterUpdateRecordRequest) (*AfterUpdateRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AfterUpdate not implemented")
}
func (UnimplementedRecordExtensionServer) BeforeDelete(context.Context, *BeforeDeleteRecordRequest) (*BeforeDeleteRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeforeDelete not implemented")
}
func (UnimplementedRecordExtensionServer) Delete(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRecordExtensionServer) AfterDelete(context.Context, *AfterDeleteRecordRequest) (*AfterDeleteRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AfterDelete not implemented")
}
func (UnimplementedRecordExtensionServer) BeforeGet(context.Context, *BeforeGetRecordRequest) (*BeforeGetRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeforeGet not implemented")
}
func (UnimplementedRecordExtensionServer) Get(context.Context, *GetRecordRequest) (*GetRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRecordExtensionServer) AfterGet(context.Context, *AfterGetRecordRequest) (*AfterGetRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AfterGet not implemented")
}
func (UnimplementedRecordExtensionServer) mustEmbedUnimplementedRecordExtensionServer() {}

// UnsafeRecordExtensionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordExtensionServer will
// result in compilation errors.
type UnsafeRecordExtensionServer interface {
	mustEmbedUnimplementedRecordExtensionServer()
}

func RegisterRecordExtensionServer(s grpc.ServiceRegistrar, srv RecordExtensionServer) {
	s.RegisterService(&RecordExtension_ServiceDesc, srv)
}

func _RecordExtension_BeforeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeListRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).BeforeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/BeforeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).BeforeList(ctx, req.(*BeforeListRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).List(ctx, req.(*ListRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_AfterList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfterListRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).AfterList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/AfterList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).AfterList(ctx, req.(*AfterListRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_BeforeCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeCreateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).BeforeCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/BeforeCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).BeforeCreate(ctx, req.(*BeforeCreateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).Create(ctx, req.(*CreateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_AfterCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfterCreateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).AfterCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/AfterCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).AfterCreate(ctx, req.(*AfterCreateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_BeforeUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeUpdateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).BeforeUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/BeforeUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).BeforeUpdate(ctx, req.(*BeforeUpdateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).Update(ctx, req.(*UpdateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_AfterUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfterUpdateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).AfterUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/AfterUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).AfterUpdate(ctx, req.(*AfterUpdateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_BeforeDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeDeleteRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).BeforeDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/BeforeDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).BeforeDelete(ctx, req.(*BeforeDeleteRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).Delete(ctx, req.(*DeleteRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_AfterDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfterDeleteRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).AfterDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/AfterDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).AfterDelete(ctx, req.(*AfterDeleteRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_BeforeGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeGetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).BeforeGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/BeforeGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).BeforeGet(ctx, req.(*BeforeGetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).Get(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordExtension_AfterGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfterGetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordExtensionServer).AfterGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ext.RecordExtension/AfterGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordExtensionServer).AfterGet(ctx, req.(*AfterGetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordExtension_ServiceDesc is the grpc.ServiceDesc for RecordExtension service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordExtension_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ext.RecordExtension",
	HandlerType: (*RecordExtensionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeforeList",
			Handler:    _RecordExtension_BeforeList_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RecordExtension_List_Handler,
		},
		{
			MethodName: "AfterList",
			Handler:    _RecordExtension_AfterList_Handler,
		},
		{
			MethodName: "BeforeCreate",
			Handler:    _RecordExtension_BeforeCreate_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RecordExtension_Create_Handler,
		},
		{
			MethodName: "AfterCreate",
			Handler:    _RecordExtension_AfterCreate_Handler,
		},
		{
			MethodName: "BeforeUpdate",
			Handler:    _RecordExtension_BeforeUpdate_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RecordExtension_Update_Handler,
		},
		{
			MethodName: "AfterUpdate",
			Handler:    _RecordExtension_AfterUpdate_Handler,
		},
		{
			MethodName: "BeforeDelete",
			Handler:    _RecordExtension_BeforeDelete_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RecordExtension_Delete_Handler,
		},
		{
			MethodName: "AfterDelete",
			Handler:    _RecordExtension_AfterDelete_Handler,
		},
		{
			MethodName: "BeforeGet",
			Handler:    _RecordExtension_BeforeGet_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RecordExtension_Get_Handler,
		},
		{
			MethodName: "AfterGet",
			Handler:    _RecordExtension_AfterGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ext/record.proto",
}
