name: binaries

on:
  push:
    tags:
      - v*
jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Build the Docker image
        uses: actions/checkout@v3
      - run: |
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=windows --build-arg ARCH=amd64 --build-arg APP=dhctl --build-arg SUFFIX=.exe --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=windows --build-arg ARCH=386 --build-arg APP=dhctl --build-arg SUFFIX=.exe --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=linux --build-arg ARCH=amd64 --build-arg APP=dhctl --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=linux --build-arg ARCH=386 --build-arg APP=dhctl --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=darwin --build-arg ARCH=amd64 --build-arg APP=dhctl --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=darwin --build-arg ARCH=arm64 --build-arg APP=dhctl --output out -f binaries.Dockerfile .
      - uses: actions/upload-artifact@v3
        with:
          name: dhctl-windows-amd64.exe
          path: out/app/output/dhctl-windows-amd64.exe
      - uses: actions/upload-artifact@v3
        with:
          name: dhctl-windows-386.exe
          path: out/app/output/dhctl-windows-386.exe
      - uses: actions/upload-artifact@v3
        with:
          name: dhctl-linux-amd64
          path: out/app/output/dhctl-linux-amd64
      - uses: actions/upload-artifact@v3
        with:
          name: dhctl-linux-386
          path: out/app/output/dhctl-linux-386
      - uses: actions/upload-artifact@v3
        with:
          name: dhctl-mac-amd64
          path: out/app/output/dhctl-darwin-amd64
      - uses: actions/upload-artifact@v3
        with:
          name: dhctl-mac-arm64
          path: out/app/output/dhctl-darwin-arm64
