name: deploy

on:
  push:
    tags:
      - v*
jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Build the Docker image
        uses: actions/checkout@v3
      - run: |
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=windows --build-arg ARCH=amd64 --build-arg APP=dhctl --build-arg SUFFIX=.exe --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=windows --build-arg ARCH=386 --build-arg APP=dhctl --build-arg SUFFIX=.exe --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=linux --build-arg ARCH=amd64 --build-arg APP=dhctl --build-arg SUFFIX=.exe --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=linux --build-arg ARCH=386 --build-arg APP=dhctl --build-arg SUFFIX=.exe --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=darwin --build-arg ARCH=amd64 --build-arg APP=dhctl --build-arg SUFFIX=.exe --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=darwin --build-arg ARCH=386 --build-arg APP=dhctl --build-arg SUFFIX=.exe --output out -f binaries.Dockerfile .
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=darwin --build-arg ARCH=arm64 --build-arg APP=dhctl --build-arg SUFFIX=.exe --output out -f binaries.Dockerfile .
      - uses: actions/upload-artifact@v3
        with:
          name: dhctl
          path: out/app/output/dhctl-*
