name: deploy

on:
  push:
    tags:
      - v*
jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Build the Docker image
        uses: actions/checkout@v3
      - run: |
          docker build . --progress=plain --no-cache --target=app -t tislib/data-handler:${GITHUB_REF##*/}
          docker build . --progress=plain --no-cache --target=app-full -t tislib/data-handler:full-${GITHUB_REF##*/}
          docker tag tislib/data-handler:${GITHUB_REF##*/} tislib/data-handler:latest
          docker tag tislib/data-handler:full-${GITHUB_REF##*/} tislib/data-handler:full-latest
          docker push tislib/data-handler:${GITHUB_REF##*/}
          docker push tislib/data-handler:full-${GITHUB_REF##*/}
          docker push tislib/data-handler:latest
          docker push tislib/data-handler:full-latest
          DOCKER_BUILDKIT=1 docker build --target=build-binaries-export --build-arg OS=windows --build-arg ARCH=amd64 --build-arg APP=dhctl --build-arg SUFFIX=.exe --output out .
      - uses: actions/upload-artifact@v3
        with:
          name: dhctl-windows-amd64.exe
          path: out/app/output/dhctl-windows-amd64.exe
