name: deploy
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Build the Docker image
        uses: actions/checkout@v3
      - run: |
          version=$(cat version)
          docker build . --progress=plain --no-cache --target=app -t tislib/apibrew:${version}
          docker build . --progress=plain --no-cache --target=apbr -t tislib/apbr:${version}
          docker tag tislib/apibrew:${version} tislib/apibrew:latest
          docker tag tislib/apbr:${version} tislib/apbr:latest
          docker push tislib/apibrew:${version}
          docker push tislib/apbr:${version}
          docker push tislib/apibrew:latest
          docker push tislib/apbr:latest

