name: deploy

on:
  push:
    tags:
      - v*
jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Build the Docker image
        uses: actions/checkout@v3
      - run: |
          docker build . --progress=plain --no-cache --target=app -t tislib/apibrew:${GITHUB_REF##*/}
          docker build . --progress=plain --no-cache --target=app-full -t tislib/apibrew:full-${GITHUB_REF##*/}
          docker tag tislib/apibrew:${GITHUB_REF##*/} tislib/apibrew:latest
          docker tag tislib/apibrew:full-${GITHUB_REF##*/} tislib/apibrew:full-latest
          docker push tislib/apibrew:${GITHUB_REF##*/}
          docker push tislib/apibrew:full-${GITHUB_REF##*/}
          docker push tislib/apibrew:latest
          docker push tislib/apibrew:full-latest
