name: ui-build

on:
  push:
    tags:
      - v*
    branches:
      - ui
  pull_request:
    branches:
      - ui
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        working-directory: ./ui
      - run: npm run lint
        working-directory: ./ui
      - run: npm run build
        working-directory: ./ui
